import type { Product } from "@/lib/data";

export const otherProducts: Product[] = [
  {
    id: "p61", slug: "now-omega-3-1000mg", brandId: "brand-009", categoryId: "cat-005",
    title: "Omega-3 Fish Oil 1000mg 200 Softgels",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSaopLcnyNAGE4wysyjVRA57ZKNDFHooRhhx8cIAlQWg&s=10",
    rating: 4.7, reviews: 9800, price: 14.4, originalPrice: 17.73,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "2 softgels",
    ingredients: ["Fish Oil Concentrate", "EPA 180mg", "DHA 120mg", "Gelatin", "Glycerin"],
    pros: ["Molecularly distilled", "Heavy metal tested", "Great value"],
    cons: ["Mild fishy aftertaste", "Large softgels"],
    bestFor: "Heart & brain health",
    warnings: "Consult if on blood thinners",
    country: "USA", manufacturer: "NOW Foods",
    labTested: true, certificationIds: ["cert-009", "cert-006", "cert-011"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 2, fiber: 0, sugar: 0, calories: 20 },
    healthScore: 94, cleanLabelScore: 96, valueScore: 95,
    dietaryInfo: { vegetarian: false, vegan: false, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Molecularly Distilled", "Heavy Metal Tested", "IFOS Certified", "Great Value"],
    aiSummary: "High-quality fish oil with optimal EPA/DHA ratio, molecularly distilled for purity and safety at an excellent price.",
  },
  {
    id: "p62", slug: "muscleblaze-omega-3", brandId: "brand-002", categoryId: "cat-005",
    title: "MuscleBlaze Omega-3 Fish Oil 120 Softgels",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYommA-I6IXM3oPickROODlPRg9UFHQW9kD9J32I364w&s=10",
    rating: 4.4, reviews: 6200, price: 7.75, originalPrice: 9.97,
    website: "HealthKart", delivery: "Free • 2 days", servingSize: "1 softgel",
    ingredients: ["Fish Oil Concentrate", "EPA 180mg", "DHA 120mg", "Gelatin"],
    pros: ["Affordable", "Good EPA/DHA ratio", "Trusted Indian brand"],
    cons: ["Lower quantity per bottle", "Basic packaging"],
    bestFor: "Daily omega-3 supplementation",
    warnings: "Store in cool dry place",
    country: "India", manufacturer: "HealthKart",
    labTested: true, certificationIds: ["cert-005", "cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 1, fiber: 0, sugar: 0, calories: 10 },
    healthScore: 88, cleanLabelScore: 85, valueScore: 94,
    dietaryInfo: { vegetarian: false, vegan: false, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Good EPA/DHA", "Affordable", "Indian Brand", "Daily Wellness"],
    aiSummary: "A budget-friendly omega-3 supplement delivering essential EPA and DHA for heart, brain, and joint health.",
  },
  {
    id: "p63", slug: "hk-vitals-omega-3", brandId: "brand-019", categoryId: "cat-005",
    title: "HK Vitals Omega-3 Fish Oil 60 Softgels",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAU19lX-EBbtIgtj_cR3CjZq6naO-HjEIBZflUCXE_1g&s=10",
    rating: 4.3, reviews: 3400, price: 4.98, originalPrice: 6.64,
    website: "HealthKart", delivery: "Free • 3 days", servingSize: "1 softgel",
    ingredients: ["Fish Oil Concentrate", "EPA 90mg", "DHA 60mg", "Gelatin"],
    pros: ["Low price", "Good for beginners", "Compact bottle"],
    cons: ["Lower potency", "Smaller serving"],
    bestFor: "Entry-level omega-3 supplementation",
    warnings: "Keep away from sunlight",
    country: "India", manufacturer: "HealthKart",
    labTested: true, certificationIds: ["cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 1, fiber: 0, sugar: 0, calories: 9 },
    healthScore: 80, cleanLabelScore: 82, valueScore: 90,
    dietaryInfo: { vegetarian: false, vegan: false, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Affordable", "Beginner Friendly", "Compact Size", "Indian Brand"],
    aiSummary: "An entry-level omega-3 supplement at an accessible price point, perfect for those starting their wellness journey.",
  },
  {
    id: "p64", slug: "gnc-fish-oil-1000mg", brandId: "brand-008", categoryId: "cat-005",
    title: "GNC Fish Oil 1000mg 90 Softgels",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnMTz8DN5LyrsR05JOfpz7Kq_JeyTS7MAu-XmDED5b5w&s=10",
    rating: 4.5, reviews: 7800, price: 22.16, originalPrice: 27.71,
    website: "GNC", delivery: "Free • 2 days", servingSize: "2 softgels",
    ingredients: ["Fish Oil Concentrate", "EPA 360mg", "DHA 240mg", "Gelatin", "Vitamin E"],
    pros: ["High potency", "Added Vitamin E", "Trusted global brand"],
    cons: ["Premium price", "Large softgels"],
    bestFor: "High-dose omega-3 needs",
    warnings: "Consult physician before use",
    country: "USA", manufacturer: "GNC Holdings",
    labTested: true, certificationIds: ["cert-006", "cert-003"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 2, fiber: 0, sugar: 0, calories: 20 },
    healthScore: 90, cleanLabelScore: 88, valueScore: 78,
    dietaryInfo: { vegetarian: false, vegan: false, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: true, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["High Potency", "Vitamin E Added", "Trusted Brand", "EPA 360mg"],
    aiSummary: "A high-potency fish oil from GNC delivering 360mg EPA and 240mg DHA per serving with added vitamin E for freshness.",
  },
  {
    id: "p65", slug: "carbamide-forte-omega-3", brandId: "brand-018", categoryId: "cat-005",
    title: "Carbamide Forte Omega-3 Fish Oil 60 Softgels",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfiYzoJ4_XQqr0CE0wN3n4C-caMEFwAO_q2nxUfLRA0A&s=10",
    rating: 4.1, reviews: 2900, price: 3.87, originalPrice: 5.53,
    website: "Amazon", delivery: "Free • 3 days", servingSize: "1 softgel",
    ingredients: ["Fish Oil Concentrate", "EPA 100mg", "DHA 50mg", "Gelatin"],
    pros: ["Lowest price", "Widely available", "Good starter"],
    cons: ["Lower potency", "Basic quality"],
    bestFor: "Budget-conscious buyers",
    warnings: "Store in cool place",
    country: "India", manufacturer: "Carbamide Forte",
    labTested: true, certificationIds: ["cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 1, fiber: 0, sugar: 0, calories: 9 },
    healthScore: 75, cleanLabelScore: 78, valueScore: 92,
    dietaryInfo: { vegetarian: false, vegan: false, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Lowest Price", "Widely Available", "Beginner Friendly"],
    aiSummary: "The most affordable omega-3 supplement on the market, suitable for those wanting essential fatty acids on a tight budget.",
  },
  {
    id: "p66", slug: "centrum-adult-multivitamin", brandId: "brand-020", categoryId: "cat-006",
    title: "Centrum Adult Multivitamin 60 Tablets",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzj9iIFvAd9Fqtt726AZZ3Q8WhmsZhJJhpoGW_tOq17g&s=10",
    rating: 4.6, reviews: 25000, price: 9.97, originalPrice: 12.18,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "1 tablet",
    ingredients: ["Vitamin C", "Vitamin D3", "Vitamin B12", "Zinc", "Magnesium", "Calcium", "Iron", "Folic Acid"],
    pros: ["Complete multivitamin", "Trusted brand worldwide", "Science-backed formula"],
    cons: ["Contains iron", "Tablets may be large"],
    bestFor: "Daily nutritional support",
    warnings: "Not a substitute for a balanced diet",
    country: "USA", manufacturer: "Pfizer",
    labTested: true, certificationIds: ["cert-006", "cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 88, cleanLabelScore: 85, valueScore: 90,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Complete Formula", "World's #1", "Science Backed", "Daily Wellness"],
    aiSummary: "The world's most trusted multivitamin, providing comprehensive nutritional support with essential vitamins and minerals.",
  },
  {
    id: "p67", slug: "muscleblaze-multivitamin", brandId: "brand-002", categoryId: "cat-006",
    title: "MuscleBlaze Multivitamin 60 Tablets",
    image: "https://cdn2.nutrabay.com/review/images/MuscleBlaze-MB-Vite-MultiVitam_34924_8726119_3.jpg",
    rating: 4.3, reviews: 8500, price: 6.09, originalPrice: 7.75,
    website: "HealthKart", delivery: "Free • 2 days", servingSize: "1 tablet",
    ingredients: ["Vitamin A", "Vitamin C", "Vitamin D3", "Vitamin E", "Zinc", "Magnesium", "Selenium", "Chromium"],
    pros: ["Affordable", "Tailored for active lifestyle", "Indian brand"],
    cons: ["Basic formulation", "No iron"],
    bestFor: "Active individuals, gym-goers",
    warnings: "Consult your physician",
    country: "India", manufacturer: "HealthKart",
    labTested: true, certificationIds: ["cert-005", "cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 82, cleanLabelScore: 80, valueScore: 93,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Affordable", "Active Lifestyle", "Indian Brand", "Essential Vitamins"],
    aiSummary: "A cost-effective multivitamin designed for India's active population, covering essential micronutrient needs.",
  },
  {
    id: "p68", slug: "gnc-mega-men", brandId: "brand-008", categoryId: "cat-006",
    title: "GNC Mega Men Multivitamin 90 Tablets",
    image: "https://cdn11.bigcommerce.com/s-ilgxsy4t82/images/stencil/original/products/348998/1274472/61hhJOKFXkL__66686.1753098774.jpg?c=1",
    rating: 4.5, reviews: 12000, price: 33.25, originalPrice: 41.01,
    website: "GNC", delivery: "Free • 2 days", servingSize: "2 tablets",
    ingredients: ["Vitamin A", "Vitamin C", "Vitamin D3", "Vitamin E", "B-Complex", "Zinc", "Selenium", "Chromium", "Lycopene"],
    pros: ["Comprehensive men's formula", "Antioxidant blend", "Energy support"],
    cons: ["Expensive", "Large tablets (2 per serving)"],
    bestFor: "Men's overall health",
    warnings: "Contains iron — keep away from children",
    country: "USA", manufacturer: "GNC Holdings",
    labTested: true, certificationIds: ["cert-006", "cert-003"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 90, cleanLabelScore: 85, valueScore: 78,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: true, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Men's Formula", "Antioxidant Blend", "Energy Support", "Premium Quality"],
    aiSummary: "GNC's flagship men's multivitamin with a comprehensive blend of vitamins, minerals, and antioxidants for peak performance.",
  },
  {
    id: "p69", slug: "centrum-women", brandId: "brand-020", categoryId: "cat-006",
    title: "Centrum Women Multivitamin 60 Tablets",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFBnFy29UIWjMyCd50HbirMjFGqj42vbblEMwwUE7mbA&s=10",
    rating: 4.5, reviews: 18500, price: 9.97, originalPrice: 12.18,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "1 tablet",
    ingredients: ["Vitamin A", "Vitamin C", "Vitamin D3", "Vitamin E", "Calcium", "Iron", "Folic Acid", "Biotin"],
    pros: ["Tailored for women", "Trusted brand", "Complete nutrition"],
    cons: ["Contains iron", "One-size approach"],
    bestFor: "Women's daily nutrition",
    warnings: "Not for men or children",
    country: "USA", manufacturer: "Pfizer",
    labTested: true, certificationIds: ["cert-006", "cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 88, cleanLabelScore: 85, valueScore: 90,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Women's Formula", "Trusted Brand", "Complete Nutrition", "Daily Support"],
    aiSummary: "Centrum's women-specific multivitamin providing tailored nutritional support with key nutrients like iron, calcium, and biotin.",
  },
  {
    id: "p70", slug: "hk-vitals-daily-multivitamin", brandId: "brand-019", categoryId: "cat-006",
    title: "HK Vitals Daily Multivitamin 90 Tablets",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVtVPPKf5beImleP_p1MHI_yCPbdTxIsnXBVAkNVK_tg&s=10",
    rating: 4.2, reviews: 4100, price: 4.42, originalPrice: 6.09,
    website: "HealthKart", delivery: "Free • 3 days", servingSize: "1 tablet",
    ingredients: ["Vitamin A", "Vitamin C", "Vitamin D3", "Vitamin E", "B-Complex", "Zinc", "Magnesium"],
    pros: ["Budget-friendly", "90-day supply", "Indian brand"],
    cons: ["Basic formula", "No iron or calcium"],
    bestFor: "Everyday nutrition on a budget",
    warnings: "Store in a cool dry place",
    country: "India", manufacturer: "HealthKart",
    labTested: true, certificationIds: ["cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 78, cleanLabelScore: 80, valueScore: 95,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["90-Day Supply", "Budget Friendly", "Indian Brand", "Essential Vitamins"],
    aiSummary: "An affordable 90-day multivitamin supply covering essential vitamins and minerals at the lowest cost per day.",
  },
  {
    id: "p71", slug: "c4-original-60serv", brandId: "brand-010", categoryId: "cat-007",
    title: "C4 Original Pre-Workout 60 Servings",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjGlzeMcT1_cQLGDz6XrN6-Y5H1Rvkz9-K_djVUIWFQg&s=10",
    rating: 4.4, reviews: 18500, price: 24.38, originalPrice: 31.03,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "6g",
    ingredients: ["Beta Alanine 1.6g", "Creatine Nitrate", "Caffeine 150mg", "Arginine AKG", "N-Acetyl Tyrosine"],
    pros: ["Explosive energy", "Great flavors", "Trusted formula"],
    cons: ["Contains artificial colors", "Tingles from beta-alanine"],
    bestFor: "High-intensity training",
    warnings: "Not for caffeine sensitive individuals",
    country: "USA", manufacturer: "Nutrabolt",
    labTested: true, certificationIds: ["cert-006", "cert-003"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 1, fat: 0, fiber: 0, sugar: 0, calories: 5 },
    healthScore: 78, cleanLabelScore: 65, valueScore: 85,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Explosive Energy", "150mg Caffeine", "Beta Alanine", "Trusted Formula"],
    aiSummary: "Popular pre-workout delivering reliable energy and focus with a clinically dosed ingredient matrix.",
  },
  {
    id: "p72", slug: "gnc-pro-performance-pre", brandId: "brand-008", categoryId: "cat-007",
    title: "GNC Pro Performance Pre-Workout 30 Servings",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_yUh2d2KqHTfoi4V9CrGHkaESqhVTnIYOX40BsbViCA&s=10",
    rating: 4.3, reviews: 6200, price: 27.71, originalPrice: 34.36,
    website: "GNC", delivery: "Free • 2 days", servingSize: "9g",
    ingredients: ["Beta Alanine 2g", "Caffeine 200mg", "Creatine HCl", "L-Citrulline", "Agmatine Sulfate"],
    pros: ["Strong energy", "Good pump ingredients", "Trusted brand"],
    cons: ["Expensive", "High caffeine may be too much"],
    bestFor: "Intense workouts, powerlifting",
    warnings: "Limit to 1 scoop per day",
    country: "USA", manufacturer: "GNC Holdings",
    labTested: true, certificationIds: ["cert-006", "cert-003"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 2, fat: 0, fiber: 0, sugar: 0, calories: 10 },
    healthScore: 76, cleanLabelScore: 68, valueScore: 75,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["200mg Caffeine", "Beta Alanine", "Pump Formula", "Premium Quality"],
    aiSummary: "A powerful pre-workout from GNC with 200mg caffeine and clinically dosed pump ingredients for serious training sessions.",
  },
  {
    id: "p73", slug: "myprotein-pre-workout", brandId: "brand-003", categoryId: "cat-007",
    title: "MyProtein Pre-Workout 50 Servings",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFg8zKgkb8Dkrx_KF8B7K30i2WRdioZucZfaj0KSYUrg&s=10",
    rating: 4.2, reviews: 9800, price: 19.94, originalPrice: 25.49,
    website: "MyProtein", delivery: "Free • 5 days", servingSize: "8g",
    ingredients: ["Beta Alanine 1.5g", "Caffeine 150mg", "L-Citrulline", "Taurine", "Green Tea Extract"],
    pros: ["Good value", "Clean ingredients", "Global brand"],
    cons: ["Milder energy", "Less pump than competitors"],
    bestFor: "Everyday training",
    warnings: "Contains caffeine",
    country: "UK", manufacturer: "The Hut Group",
    labTested: true, certificationIds: ["cert-002", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 1, fat: 0, fiber: 0, sugar: 0, calories: 5 },
    healthScore: 82, cleanLabelScore: 78, valueScore: 85,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Good Value", "Clean Ingredients", "Global Brand", "Everyday Energy"],
    aiSummary: "A balanced pre-workout with clean ingredients from MyProtein, offering reliable energy and focus for daily training.",
  },
  {
    id: "p74", slug: "muscleblaze-pre-workout", brandId: "brand-002", categoryId: "cat-007",
    title: "MuscleBlaze Pre-Workout 30 Servings",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvMI1l3EmwqaZETVftrg75JXZBstah6R_Fz94C8N8x1Q&s=10",
    rating: 4.3, reviews: 7400, price: 14.4, originalPrice: 18.28,
    website: "HealthKart", delivery: "Free • 2 days", servingSize: "7g",
    ingredients: ["Beta Alanine 1g", "Caffeine 120mg", "Citrulline Malate", "Creatine", "Tyrosine"],
    pros: ["Affordable", "Good ingredient profile", "Indian brand"],
    cons: ["Lower caffeine", "Milder effect"],
    bestFor: "Budget-conscious athletes",
    warnings: "Not for pregnant women",
    country: "India", manufacturer: "HealthKart",
    labTested: true, certificationIds: ["cert-005", "cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 1, fat: 0, fiber: 0, sugar: 0, calories: 5 },
    healthScore: 78, cleanLabelScore: 75, valueScore: 92,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Affordable", "Good Profile", "Indian Brand", "Training Energy"],
    aiSummary: "A value-packed pre-workout from India's leading brand, delivering solid energy and pump ingredients at a budget-friendly price.",
  },
  {
    id: "p75", slug: "dymatize-pre-wo", brandId: "brand-004", categoryId: "cat-007",
    title: "Dymatize Pre-Workout 40 Servings",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbFdstkCE9AUZ9Q67An3Jrl0Seol8cJ3161PpTSXljzA&s=10",
    rating: 4.5, reviews: 5100, price: 33.25, originalPrice: 41.01,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "10g",
    ingredients: ["Beta Alanine 2g", "Caffeine 250mg", "L-Citrulline 6g", "Creatine HCl", "Theanine"],
    pros: ["High stimulant", "Great pump", "Premium quality"],
    cons: ["Expensive", "Very high caffeine"],
    bestFor: "Elite athletes, heavy training",
    warnings: "Limit to half scoop if sensitive",
    country: "USA", manufacturer: "Dymatize Nutrition",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 2, fat: 0, fiber: 0, sugar: 0, calories: 10 },
    healthScore: 80, cleanLabelScore: 72, valueScore: 75,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["250mg Caffeine", "6g Citrulline", "Premium Quality", "Elite Performance"],
    aiSummary: "A high-performance pre-workout from Dymatize with maximum dosed ingredients for serious athletes demanding the best.",
  },
  {
    id: "p76", slug: "optimum-serious-mass", brandId: "brand-001", categoryId: "cat-004",
    title: "Optimum Nutrition Serious Mass 6kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRR1jEx9Oo_qEqLqLiE6veXjuAMuu1EGbWq3Qccn2IwEQ&s=10",
    rating: 4.5, reviews: 14200, price: 55.42, originalPrice: 68.73,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "150g",
    ingredients: ["Whey Protein Concentrate", "Maltodextrin", "Sugar", "Vitamins & Minerals", "Creatine"],
    pros: ["High calorie (1250 cal)", "Good for bulking", "Trusted brand"],
    cons: ["High sugar", "Large serving size"],
    bestFor: "Hardgainers, bulking phase",
    warnings: "Not for weight loss",
    country: "USA", manufacturer: "Glanbia Performance Nutrition",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 50, carbs: 254, fat: 2.5, fiber: 1, sugar: 40, calories: 1250 },
    healthScore: 65, cleanLabelScore: 55, valueScore: 85,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: false, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: true, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["1250 Calories", "50g Protein", "Bulking Formula", "Trusted Brand"],
    aiSummary: "The gold standard mass gainer delivering 1250 calories per serving with 50g protein for serious weight gain.",
  },
  {
    id: "p77", slug: "muscleblaze-mass-gainer", brandId: "brand-002", categoryId: "cat-004",
    title: "MuscleBlaze Mass Gainer 5kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-cEzt2293vVOkdjaRqjaPWUpdyPvTLD8tq-Ji3G3JJg&s=10",
    rating: 4.3, reviews: 8900, price: 33.25, originalPrice: 41.56,
    website: "HealthKart", delivery: "Free • 2 days", servingSize: "130g",
    ingredients: ["Whey Protein Concentrate", "Maltodextrin", "Oats", "Cocoa", "Vitamins"],
    pros: ["Affordable", "Indian brand", "Oat blend for complex carbs"],
    cons: ["Moderate sugar", "Large volume"],
    bestFor: "Bulking on a budget",
    warnings: "Use as supplement not meal replacement",
    country: "India", manufacturer: "HealthKart",
    labTested: true, certificationIds: ["cert-005", "cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 40, carbs: 200, fat: 3, fiber: 2, sugar: 25, calories: 1000 },
    healthScore: 68, cleanLabelScore: 60, valueScore: 92,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: false, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: true, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["1000 Calories", "40g Protein", "Oat Blend", "Great Value"],
    aiSummary: "A value-packed mass gainer with oat-based carbohydrates and 40g protein per serving for affordable weight gain.",
  },
  {
    id: "p78", slug: "bsn-true-mass", brandId: "brand-014", categoryId: "cat-004",
    title: "BSN True Mass 4.5kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8k86V9LMdljjSPrFIUnVf3C2RR5eYcU85ogSBh0-7nQ&s=10",
    rating: 4.4, reviews: 6800, price: 49.88, originalPrice: 62.07,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "130g",
    ingredients: ["Whey Protein Isolate", "Milk Protein Concentrate", "Maltodextrin", "Medium Chain Triglycerides"],
    pros: ["Superior protein blend", "Great taste", "MCTs for healthy fats"],
    cons: ["Expensive", "High calories per serving"],
    bestFor: "Clean bulking",
    warnings: "Contains milk and soy",
    country: "USA", manufacturer: "BSN",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 50, carbs: 160, fat: 5, fiber: 1, sugar: 18, calories: 1050 },
    healthScore: 72, cleanLabelScore: 68, valueScore: 80,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: false, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: true, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["50g Protein", "Superior Blend", "Great Taste", "MCTs Included"],
    aiSummary: "Premium mass gainer from BSN with a superior multi-source protein blend and MCTs for healthier weight gain.",
  },
  {
    id: "p79", slug: "yogabar-protein-bar", brandId: "brand-036", categoryId: "cat-009",
    title: "Yoga Bar Protein Bar 40g — 12 Pack",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4iY1Kk7g_4LESs87G-nWCAlhD5sQMsatLqWcnhI27Zg&s=10",
    rating: 4.3, reviews: 4200, price: 6.64, originalPrice: 8.3,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "1 bar (40g)",
    ingredients: ["Oats", "Peanuts", "Whey Protein Isolate", "Honey", "Jaggery", "Cocoa"],
    pros: ["Natural ingredients", "No artificial sweeteners", "Indian brand"],
    cons: ["Higher sugar from natural sources", "Moderate protein"],
    bestFor: "Healthy snacking, post-workout",
    warnings: "Contains peanuts and milk",
    country: "India", manufacturer: "Yoga Bar",
    labTested: true, certificationIds: ["cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 10, carbs: 22, fat: 8, fiber: 3, sugar: 12, calories: 200 },
    healthScore: 78, cleanLabelScore: 90, valueScore: 85,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: false, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: true, containsGluten: true, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["Natural Ingredients", "No Artificial Sweeteners", "Indian Brand", "Post-Workout Snack"],
    aiSummary: "A clean-label protein bar made with natural ingredients like oats, peanuts, and honey — no artificial anything.",
  },
  {
    id: "p80", slug: "ritebite-protein-bar", brandId: "brand-040", categoryId: "cat-009",
    title: "RiteBite Max Protein Bar 50g — 6 Pack",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1O0xm5LAl_2YBpzocDgL4ugmmfDsF-3o1GF-Zkb9dPQ&s=10",
    rating: 4.4, reviews: 5800, price: 4.98, originalPrice: 6.64,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "1 bar (50g)",
    ingredients: ["Whey Protein Isolate", "Milk Protein Concentrate", "Oats", "Peanuts", "Cocoa Butter", "Stevia"],
    pros: ["High protein (15g)", "Low sugar", "Great taste"],
    cons: ["Contains sugar alcohols", "Firmer texture"],
    bestFor: "Post-workout protein, on-the-go",
    warnings: "Contains milk and peanuts",
    country: "India", manufacturer: "RiteBite",
    labTested: true, certificationIds: ["cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 15, carbs: 18, fat: 9, fiber: 2, sugar: 2, calories: 210 },
    healthScore: 82, cleanLabelScore: 80, valueScore: 90,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: false, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: true, containsGluten: true, containsLactose: true, containsSugarAlcohol: true },
    highlights: ["15g Protein", "Low Sugar", "Great Taste", "High Protein Bar"],
    aiSummary: "A delicious high-protein bar with 15g protein and only 2g sugar, perfect for post-workout recovery without the sugar crash.",
  },
  {
    id: "p81", slug: "myprotein-protein-bar", brandId: "brand-003", categoryId: "cat-009",
    title: "MyProtein Protein Bar 60g — 12 Pack",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiDKnSu9hp6wTZs9pBSmKdDu9ncc0nCS6NFzanSuo9Jg&s=10",
    rating: 4.3, reviews: 7200, price: 27.71, originalPrice: 34.36,
    website: "MyProtein", delivery: "Free • 5 days", servingSize: "1 bar (60g)",
    ingredients: ["Whey Protein Isolate", "Soy Protein Isolate", "Collagen Hydrolysate", "Cocoa", "Glycerol"],
    pros: ["High protein (20g)", "Multiple layers", "Global brand"],
    cons: ["Higher calories", "Contains soy"],
    bestFor: "Meal replacement, high protein needs",
    warnings: "Contains milk, soy, gluten",
    country: "UK", manufacturer: "The Hut Group",
    labTested: true, certificationIds: ["cert-002", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 20, carbs: 25, fat: 10, fiber: 1, sugar: 8, calories: 260 },
    healthScore: 75, cleanLabelScore: 72, valueScore: 78,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: false, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: true, containsLactose: true, containsSugarAlcohol: true },
    highlights: ["20g Protein", "Multi-Layer", "Global Brand", "Meal Replacement"],
    aiSummary: "A satisfying multi-layer protein bar with 20g protein from MyProtein, ideal for curbing hunger and building muscle.",
  },
  {
    id: "p82", slug: "the-whole-truth-bar", brandId: "brand-041", categoryId: "cat-009",
    title: "The Whole Truth Protein Bar 35g — 6 Pack",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8K9ZIRbMRBmwvfcfNoo7YW0Sq9zB8XkiS4ulSU39fAg&s=10",
    rating: 4.5, reviews: 3100, price: 6.09, originalPrice: 7.75,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "1 bar (35g)",
    ingredients: ["Dates", "Almonds", "Whey Protein Isolate", "Cocoa", "Sea Salt"],
    pros: ["100% clean label", "No additives", "Real food ingredients"],
    cons: ["Smaller bar", "Higher sugar from dates"],
    bestFor: "Clean eating, real food advocates",
    warnings: "Contains nuts and milk",
    country: "India", manufacturer: "The Whole Truth Foods",
    labTested: true, certificationIds: ["cert-008", "cert-014"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 8, carbs: 18, fat: 5, fiber: 2, sugar: 12, calories: 140 },
    healthScore: 85, cleanLabelScore: 98, valueScore: 80,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["100% Clean Label", "Real Food", "No Additives", "Honest Ingredients"],
    aiSummary: "The cleanest protein bar on the market with just 5 real-food ingredients — dates, almonds, whey, cocoa, and salt.",
  },
  {
    id: "p83", slug: "muscleblaze-protein-bar", brandId: "brand-002", categoryId: "cat-009",
    title: "MuscleBlaze Protein Bar 30g — 6 Pack",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhrPOsCTEeoXIjch1DWSFiGHfa4UdPOyQe1stq_l41Xw&s",
    rating: 4.2, reviews: 3800, price: 4.42, originalPrice: 5.53,
    website: "HealthKart", delivery: "Free • 2 days", servingSize: "1 bar (30g)",
    ingredients: ["Whey Protein Concentrate", "Oats", "Peanuts", "Cocoa", "Maltitol"],
    pros: ["Affordable", "Decent protein", "Indian brand"],
    cons: ["Contains sugar alcohols", "Firm texture"],
    bestFor: "Budget protein bar option",
    warnings: "Contains milk and peanuts",
    country: "India", manufacturer: "HealthKart",
    labTested: true, certificationIds: ["cert-005", "cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 12, carbs: 20, fat: 7, fiber: 2, sugar: 3, calories: 190 },
    healthScore: 72, cleanLabelScore: 70, valueScore: 92,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: false, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: true, containsGluten: true, containsLactose: true, containsSugarAlcohol: true },
    highlights: ["12g Protein", "Affordable", "Indian Brand", "Good Value"],
    aiSummary: "A budget-friendly protein bar from India's leading sports nutrition brand, offering solid nutrition at an accessible price.",
  },
  {
    id: "p84", slug: "pintola-peanut-butter", brandId: "brand-037", categoryId: "cat-011",
    title: "Pintola All-Natural Peanut Butter 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjhaa7louHO9k2ZCJzw2BwfQq2Kn5ZYCCouT8PfVQEqw&s=10",
    rating: 4.5, reviews: 18500, price: 6.64, originalPrice: 8.3,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "30g",
    ingredients: ["Roasted Peanuts", "Sea Salt"],
    pros: ["100% natural", "No added sugar", "No palm oil"],
    cons: ["Oil separation natural", "May need stirring"],
    bestFor: "Clean eating, daily protein source",
    warnings: "Contains peanuts, may contain traces of other nuts",
    country: "India", manufacturer: "Pintola",
    labTested: true, certificationIds: ["cert-008", "cert-014"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 8, carbs: 6, fat: 16, fiber: 2, sugar: 1, calories: 190 },
    healthScore: 88, cleanLabelScore: 98, valueScore: 95,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["100% Natural", "No Added Sugar", "No Palm Oil", "Best Seller"],
    aiSummary: "India's best-selling natural peanut butter with just two ingredients — roasted peanuts and sea salt. No sugar, no palm oil.",
  },
  {
    id: "p85", slug: "alpino-peanut-butter", brandId: "brand-038", categoryId: "cat-011",
    title: "Alpino Peanut Butter Smooth 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsUyUAcIkjTQRyuDlMz8GgzQ8yPYNuSl_m9KGeEgBrSg&s=10",
    rating: 4.4, reviews: 9200, price: 6.09, originalPrice: 7.75,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "30g",
    ingredients: ["Roasted Peanuts", "Sugar", "Salt", "Palm Oil"],
    pros: ["Smooth texture", "Good taste", "Affordable"],
    cons: ["Contains added sugar", "Contains palm oil"],
    bestFor: "Everyday peanut butter lovers",
    warnings: "Contains peanuts",
    country: "India", manufacturer: "Alpino",
    labTested: true, certificationIds: ["cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 7, carbs: 8, fat: 15, fiber: 1.5, sugar: 4, calories: 185 },
    healthScore: 72, cleanLabelScore: 68, valueScore: 92,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Smooth Texture", "Affordable", "Great Taste", "Popular Brand"],
    aiSummary: "A popular, affordable peanut butter with a smooth, spreadable texture that the whole family loves.",
  },
  {
    id: "p86", slug: "the-whole-truth-peanut-butter", brandId: "brand-041", categoryId: "cat-011",
    title: "The Whole Truth Peanut Butter 500g",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWyDgZLce1lBJPUuyWzP_W0AC6AOqYbr5bOxAn08Q85w&s",
    rating: 4.6, reviews: 4500, price: 4.42, originalPrice: 5.53,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "30g",
    ingredients: ["Peanuts"],
    pros: ["Single ingredient", "Absolutely nothing added", "Cleanest label possible"],
    cons: ["Higher price per gram", "Natural oil separation"],
    bestFor: "Minimalist eaters, health purists",
    warnings: "Contains peanuts",
    country: "India", manufacturer: "The Whole Truth Foods",
    labTested: true, certificationIds: ["cert-008", "cert-014"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 8, carbs: 5, fat: 16, fiber: 2, sugar: 1, calories: 185 },
    healthScore: 92, cleanLabelScore: 100, valueScore: 82,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["100% Peanuts", "Single Ingredient", "No Added Anything", "Cleanest Label"],
    aiSummary: "The purest peanut butter available — made from 100% peanuts with absolutely nothing else added.",
  },
  {
    id: "p87", slug: "quaker-oats-1kg", brandId: "brand-043", categoryId: "cat-012",
    title: "Quaker Oats Rolled Oats 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmuBv5VPpYInqTSFXoe9ocfNV5TKND-NwUz8wr4s3ItA&s",
    rating: 4.6, reviews: 32000, price: 2.76, originalPrice: 3.31,
    website: "Amazon", delivery: "Free • 1 day", servingSize: "40g",
    ingredients: ["100% Rolled Oats"],
    pros: ["Heart healthy", "Rich in fiber", "Trusted brand for decades"],
    cons: ["Contains gluten", "Basic product"],
    bestFor: "Healthy breakfast, weight management",
    warnings: "Contains gluten (oats)",
    country: "USA", manufacturer: "Quaker",
    labTested: true, certificationIds: ["cert-008", "cert-014"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 5, carbs: 27, fat: 2.5, fiber: 4, sugar: 1, calories: 150 },
    healthScore: 90, cleanLabelScore: 98, valueScore: 96,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: false, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: true, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["100% Oats", "Heart Healthy", "High Fiber", "Trusted Brand"],
    aiSummary: "America's favorite oats for over a century — 100% whole grain rolled oats for a heart-healthy, fiber-rich breakfast.",
  },
  {
    id: "p88", slug: "kelloggs-oats-500g", brandId: "brand-042", categoryId: "cat-012",
    title: "Kellogg's Oats 500g",
    image: "https://rukmini1.flixcart.com/image/1500/1500/jybvafk0/cereal-flake/5/u/a/500-oats-500g-pouch-kellogg-s-original-imafghf5bzmjuafn.jpeg?q=70",
    rating: 4.4, reviews: 8500, price: 179, originalPrice: 2.54,
    website: "Amazon", delivery: "Free • 1 day", servingSize: "40g",
    ingredients: ["Whole Grain Oats"],
    pros: ["Affordable", "Good quality", "Quick cooking"],
    cons: ["Limited availability in some stores", "Basic packaging"],
    bestFor: "Everyday oatmeal breakfast",
    warnings: "Contains gluten",
    country: "USA", manufacturer: "Kellogg's",
    labTested: true, certificationIds: ["cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 5, carbs: 26, fat: 2, fiber: 3.5, sugar: 1, calories: 145 },
    healthScore: 88, cleanLabelScore: 96, valueScore: 94,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: false, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: true, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Whole Grain", "Affordable", "Quick Cooking", "Trusted Brand"],
    aiSummary: "Kellogg's whole grain oats for a quick, nutritious breakfast at an affordable price.",
  },
  {
    id: "p89", slug: "true-elements-oats", brandId: "brand-039", categoryId: "cat-012",
    title: "True Elements Rolled Oats 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtmgNcK5IeaIrTHkWIslU0uzdZgnrdrFGL9il0LVbZqw&s",
    rating: 4.5, reviews: 6200, price: 3.31, originalPrice: 4.2,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "40g",
    ingredients: ["100% Rolled Oats"],
    pros: ["Indian brand", "Premium quality", "Good value 1kg"],
    cons: ["Similar to other oats", "Premium pricing against competitors"],
    bestFor: "Clean eating breakfast",
    warnings: "Contains gluten",
    country: "India", manufacturer: "True Elements",
    labTested: true, certificationIds: ["cert-008", "cert-014"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 5, carbs: 27, fat: 2.5, fiber: 4, sugar: 1, calories: 150 },
    healthScore: 90, cleanLabelScore: 98, valueScore: 90,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: false, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: true, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["100% Oats", "Indian Brand", "Premium Quality", "High Fiber"],
    aiSummary: "Premium rolled oats from an Indian clean-food brand, offering the same whole grain goodness with local quality assurance.",
  },
  {
    id: "p90", slug: "minimalist-vitamin-c-serum", brandId: "brand-022", categoryId: "cat-019",
    title: "Minimalist 10% Vitamin C Serum 30ml",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuuUUXNzFninD8SkZmDUxm4DPqbKxbK6kvXGrwiTUr6w&s",
    rating: 4.5, reviews: 15200, price: 6.64, originalPrice: 8.3,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "3-4 drops",
    ingredients: ["Ethyl Ascorbic Acid 10%", "Ferulic Acid", "Vitamin E", "Propanediol", "Purified Water"],
    pros: ["Stable vitamin C derivative", "Transparent formulation", "Great results"],
    cons: ["Small bottle", "May oxidize over time"],
    bestFor: "Brightening, anti-aging, even skin tone",
    warnings: "Use sunscreen in AM routine",
    country: "India", manufacturer: "Minimalist",
    labTested: true, certificationIds: ["cert-010", "cert-012"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 85, cleanLabelScore: 92, valueScore: 90,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Vitamin C 10%", "Transparent Label", "Brightening", "Anti-Aging"],
    aiSummary: "A science-backed vitamin C serum with stable 10% ethyl ascorbic acid, ferulic acid, and vitamin E for bright, youthful skin.",
  },
  {
    id: "p91", slug: "cetaphil-gentle-cleanser", brandId: "brand-023", categoryId: "cat-017",
    title: "Cetaphil Gentle Skin Cleanser 500ml",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfILbKfA7SvxnTSuf6iRozkzv-RefJdUhLPNfQIdoJPQ&s=10",
    rating: 4.7, reviews: 28000, price: 9.41, originalPrice: 11.63,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "Pump",
    ingredients: ["Water", "Cetyl Alcohol", "Propylene Glycol", "Sodium Lauryl Sulfate", "Parabens"],
    pros: ["Dermatologist recommended", "Gentle on sensitive skin", "Non-comedogenic"],
    cons: ["Contains SLS", "May not remove heavy makeup well"],
    bestFor: "Sensitive skin, daily cleansing",
    warnings: "For external use only",
    country: "USA", manufacturer: "Galderma",
    labTested: true, certificationIds: ["cert-010", "cert-012"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 82, cleanLabelScore: 75, valueScore: 92,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Dermatologist Recommended", "Gentle", "Non-Comedogenic", "Sensitive Skin"],
    aiSummary: "The world's most recommended gentle cleanser by dermatologists — non-comedogenic, fragrance-free, and perfect for sensitive skin.",
  },
  {
    id: "p92", slug: "cerave-hydrating-cleanser", brandId: "brand-024", categoryId: "cat-017",
    title: "CeraVe Hydrating Facial Cleanser 473ml",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSb6dIIN7xi9vFWD8IkywaRHwpdyTb4Rg6mCcLRfaXvdg&s",
    rating: 4.6, reviews: 22000, price: 14.4, originalPrice: 17.73,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "Pump",
    ingredients: ["Ceramides", "Glycerin", "Hyaluronic Acid", "MVE Technology", "Water"],
    pros: ["Contains ceramides", "Hydrating formula", "Non-comedogenic"],
    cons: ["Premium price", "May not suit very oily skin"],
    bestFor: "Dry to normal skin, barrier repair",
    warnings: "For external use only",
    country: "USA", manufacturer: "L'Oréal",
    labTested: true, certificationIds: ["cert-010", "cert-012"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 88, cleanLabelScore: 85, valueScore: 82,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Ceramides", "Hydrating", "Barrier Repair", "Dermatologist Developed"],
    aiSummary: "A dermatologist-developed hydrating cleanser with essential ceramides and hyaluronic acid for gentle, effective cleansing.",
  },
  {
    id: "p93", slug: "minimalist-sunscreen-spf50", brandId: "brand-022", categoryId: "cat-020",
    title: "Minimalist Sunscreen SPF 50 PA+++ 50ml",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHFcgqGkqKfVfVFE9bHJrgFr_Rdlx4kNNaj62Vm74r6w&s",
    rating: 4.4, reviews: 8500, price: 4.98, originalPrice: 6.09,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "Pea-sized",
    ingredients: ["Zinc Oxide", "Enzacamene", "Vitamin E", "Aloe Vera", "Green Tea Extract"],
    pros: ["Broad spectrum SPF50", "Zinc-based", "Lightweight"],
    cons: ["White cast possible", "Small bottle"],
    bestFor: "Daily sun protection",
    warnings: "Reapply every 2 hours in sun",
    country: "India", manufacturer: "Minimalist",
    labTested: true, certificationIds: ["cert-010", "cert-012"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 88, cleanLabelScore: 90, valueScore: 88,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["SPF 50 PA+++", "Zinc-Based", "Lightweight", "Daily Protection"],
    aiSummary: "A lightweight, zinc-based sunscreen with broad spectrum SPF50 protection that won't clog pores or feel heavy.",
  },
  {
    id: "p94", slug: "cerave-moisturizing-cream", brandId: "brand-024", categoryId: "cat-018",
    title: "CeraVe Moisturizing Cream 454g",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaAstKG1Xm6k8zejZnknvyYAoOSGvWt6VX5HFnE63XRw&s=10",
    rating: 4.7, reviews: 25000, price: 17.73, originalPrice: 21.61,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "Dime-sized",
    ingredients: ["Ceramides", "Hyaluronic Acid", "Glycerin", "MVE Technology", "Dimethicone"],
    pros: ["Contains 3 essential ceramides", "24-hour hydration", "Non-comedogenic"],
    cons: ["Thick texture", "Premium price"],
    bestFor: "Dry skin, eczema-prone skin",
    warnings: "For external use only",
    country: "USA", manufacturer: "L'Oréal",
    labTested: true, certificationIds: ["cert-010", "cert-012"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 90, cleanLabelScore: 85, valueScore: 85,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["3 Ceramides", "24H Hydration", "Non-Comedogenic", "Dermatologist Developed"],
    aiSummary: "A cult-favorite moisturizer with 3 essential ceramides and hyaluronic acid for 24-hour hydration and skin barrier repair.",
  },
  {
    id: "p95", slug: "neutrogena-sunscreen-spf50", brandId: "brand-025", categoryId: "cat-020",
    title: "Neutrogena Ultra Sheer Dry Touch SPF 50 88ml",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2uta4kNeguJF5cJmlSKPGddN7dee5aHdYv5yAdk5wnQ&s=10",
    rating: 4.5, reviews: 18000, price: 9.97, originalPrice: 12.18,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "Pea-sized",
    ingredients: ["Avobenzone", "Homosalate", "Octisalate", "Octocrylene", "Helioplex Technology"],
    pros: ["Dry touch finish", "High SPF", "Trusted brand"],
    cons: ["Chemical sunscreen", "Some may find it drying"],
    bestFor: "Oily skin, daily sun protection",
    warnings: "Avoid contact with eyes",
    country: "USA", manufacturer: "Johnson & Johnson",
    labTested: true, certificationIds: ["cert-010"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 84, cleanLabelScore: 72, valueScore: 85,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["SPF 50", "Dry Touch", "Trusted Brand", "Helioplex Technology"],
    aiSummary: "A best-selling sunscreen with Helioplex technology for superior UVA/UVB protection with a non-greasy, dry-touch finish.",
  },
  {
    id: "p96", slug: "bioderma-sensibio-h2o", brandId: "brand-026", categoryId: "cat-017",
    title: "Bioderma Sensibio H2O Micellar Water 500ml",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU4jRvNpz2nQMbV5wyILjaKaGUaC0lC5W8AQU938bUww&s=10",
    rating: 4.8, reviews: 21000, price: 16.62, originalPrice: 19.94,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "Cotton pad",
    ingredients: ["MICELLE Technology", "Cucumber Extract", "Mannitol", "Water"],
    pros: ["No rinse needed", "Gentle cleansing", "Suitable for sensitive eyes"],
    cons: ["Expensive", "Large bottle but finishes quickly"],
    bestFor: "Sensitive skin, makeup removal",
    warnings: "For external use only",
    country: "France", manufacturer: "NAOS Group",
    labTested: true, certificationIds: ["cert-010", "cert-012"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 90, cleanLabelScore: 88, valueScore: 78,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["No Rinse", "Gentle", "Sensitive Eyes", "Dermatological Brand"],
    aiSummary: "The original micellar water, Sensibio H2O is a French pharmacy favorite for gentle, effective cleansing without rinsing.",
  },
  {
    id: "p97", slug: "cosrx-snail-mucin", brandId: "brand-027", categoryId: "cat-019",
    title: "COSRX Snail 96 Mucin Power Essence 100ml",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqm7ZRTwoKDyS7OCR2HrJbz75LaAm7MlCQZ0VicOniow&s=10",
    rating: 4.7, reviews: 14500, price: 14.4, originalPrice: 17.73,
    website: "Amazon", delivery: "Free • 3 days", servingSize: "2-3 drops",
    ingredients: ["Snail Secretion Filtrate 96%", "Sodium Hyaluronate", "Allantoin", "Panthenol"],
    pros: ["K-beauty cult favorite", "Highly hydrating", "Barrier repairing"],
    cons: ["Texture may not suit everyone", "Premium price"],
    bestFor: "Hydration, skin barrier repair, anti-aging",
    warnings: "Patch test recommended",
    country: "South Korea", manufacturer: "COSRX",
    labTested: true, certificationIds: ["cert-010", "cert-012", "cert-013"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 88, cleanLabelScore: 90, valueScore: 82,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["96% Snail Mucin", "K-Beauty Hit", "Hydrating", "Barrier Repair"],
    aiSummary: "A K-beauty sensation featuring 96% snail mucin for intense hydration, skin repair, and a radiant, glass-skin glow.",
  },
  {
    id: "p98", slug: "dot-key-vitamin-c", brandId: "brand-028", categoryId: "cat-019",
    title: "Dot & Key Vitamin C + E Serum 30ml",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3X9XXV8DnlKxj6Kpr2Oq-wtoK1bo1M4Z6BifGhrV2YA&s=10",
    rating: 4.3, reviews: 7200, price: 5.53, originalPrice: 7.2,
    website: "Nykaa", delivery: "Free • 2 days", servingSize: "3-4 drops",
    ingredients: ["Vitamin C (Ascorbic Acid)", "Vitamin E", "Ferulic Acid", "Hyaluronic Acid"],
    pros: ["Affordable vitamin C", "Good formulation", "Indian brand"],
    cons: ["Basic packaging", "May oxidize faster"],
    bestFor: "Brightening and daily antioxidant protection",
    warnings: "Store in a cool, dark place",
    country: "India", manufacturer: "Dot & Key",
    labTested: true, certificationIds: ["cert-010"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 80, cleanLabelScore: 82, valueScore: 92,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Vitamin C", "Affordable", "Indian Brand", "Brightening"],
    aiSummary: "An affordable vitamin C serum from a popular Indian skincare brand, delivering brightening antioxidants at a friendly price.",
  },
  {
    id: "p99", slug: "plum-green-tea-moisturizer", brandId: "brand-030", categoryId: "cat-018",
    title: "Plum Green Tea Mattifying Moisturizer 75ml",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdfy_9Jzgr2IP2_aRkfEN9BTiqrMVEsrtpaorfho3C4A&s",
    rating: 4.3, reviews: 9800, price: 4.42, originalPrice: 5.53,
    website: "Nykaa", delivery: "Free • 2 days", servingSize: "Pea-sized",
    ingredients: ["Green Tea Extract", "Salicylic Acid", "Niacinamide", "Aloe Vera", "Glycerin"],
    pros: ["Mattifying for oily skin", "Contains niacinamide", "Cruelty-free"],
    cons: ["Lightweight for dry skin", "May pill with some products"],
    bestFor: "Oily, acne-prone skin types",
    warnings: "For external use only",
    country: "India", manufacturer: "Plum",
    labTested: true, certificationIds: ["cert-010", "cert-013"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 82, cleanLabelScore: 85, valueScore: 92,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Green Tea", "Mattifying", "Niacinamide", "Cruelty Free"],
    aiSummary: "A lightweight, mattifying moisturizer with green tea and niacinamide, perfect for oily and combination skin types.",
  },
];