import type { Product } from "@/lib/data";

export const supplementProducts: Product[] = [
  // ─── WHEY PROTEIN (40 products) ───
  {
    id: "p7", slug: "dymatize-iso100-5lb", brandId: "brand-004", categoryId: "cat-002",
    title: "ISO100 Hydrolyzed Whey Protein Isolate 5lb",
    image: "https://proteinxpressindia.com/wp-content/uploads/2024/08/817NNI4NLbL._SL1500_.jpg",
    rating: 4.8, reviews: 18450, price: 66.51, originalPrice: 83.14,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "29g",
    ingredients: ["Hydrolyzed Whey Protein Isolate", "Cocoa", "Natural Flavors", "Lecithin", "Salt"],
    pros: ["25g protein per serving", "Zero sugar", "Hydrolyzed for fast absorption", "Gluten-free"],
    cons: ["Premium price point", "Limited flavor availability"],
    bestFor: "Post-workout recovery, lean muscle building",
    warnings: "Contains milk ingredients",
    country: "USA", manufacturer: "Dymatize Nutrition",
    labTested: true, certificationIds: ["cert-001", "cert-006", "cert-003"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 25, carbs: 1, fat: 0.5, fiber: 0, sugar: 0, calories: 110 },
    healthScore: 95, cleanLabelScore: 93, valueScore: 82,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["25g Protein", "Zero Sugar", "Hydrolyzed", "Gluten Free"],
    aiSummary: "Premium hydrolyzed whey isolate with rapid absorption, zero sugar, and 25g of pure protein per serving. Ideal for serious athletes.",
  },
  {
    id: "p8", slug: "muscleblaze-100-whey-1kg", brandId: "brand-002", categoryId: "cat-002",
    title: "MuscleBlaze 100% Whey Protein 1kg",
    image: "https://imgs.search.brave.com/kTH6wuaoXs3wSIZ4gCEO6vjIlYwQEyE2a23pVyiL0B4/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDFsWjJLVnI3R0wu/anBn",
    rating: 4.6, reviews: 32000, price: 43, originalPrice: 47.44,
    website: "HealthKart", delivery: "Free • 2 days", servingSize: "32g",
    ingredients: ["Whey Protein Concentrate", "Whey Protein Isolate", "Cocoa", "Sucralose"],
    pros: ["Great value for money", "Good mix of isolate + concentrate", "Trusted Indian brand"],
    cons: ["Contains artificial sweetener", "Not suitable for lactose intolerant"],
    bestFor: "General muscle building and recovery",
    warnings: "Store in cool dry place",
    country: "India", manufacturer: "HealthKart",
    labTested: true, certificationIds: ["cert-005", "cert-008", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 24, carbs: 5, fat: 1.5, fiber: 0, sugar: 2, calories: 135 },
    healthScore: 88, cleanLabelScore: 80, valueScore: 95,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["24g Protein", "Great Value", "Trusted Brand", "Mix of Isolate"],
    aiSummary: "India's best-selling whey protein offering solid nutrition at an affordable price point with 24g protein per serving.",
  },
  {
    id: "p9", slug: "myprotein-impact-whey-2.5kg", brandId: "brand-003", categoryId: "cat-002",
    title: "Impact Whey Protein 2.5kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1sularlP2b2rzPebBZGCG7-836njiNzy8KlOsSqETIA&s=10",
    rating: 4.5, reviews: 45000, price: 43.23, originalPrice: 53.2,
    website: "MyProtein", delivery: "Free • 5 days", servingSize: "25g",
    ingredients: ["Whey Protein Concentrate", "Whey Protein Isolate", "Natural Flavors", "Lecithin"],
    pros: ["60+ flavors available", "Global brand", "Consistent quality"],
    cons: ["International shipping delays", "Mixed with concentrate"],
    bestFor: "Daily protein supplementation",
    warnings: "Contains milk derivatives",
    country: "UK", manufacturer: "The Hut Group",
    labTested: true, certificationIds: ["cert-002", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 21, carbs: 3, fat: 1.9, fiber: 0.3, sugar: 1, calories: 115 },
    healthScore: 87, cleanLabelScore: 85, valueScore: 90,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["21g Protein", "60+ Flavors", "Global Brand", "Consistent Quality"],
    aiSummary: "One of the most popular whey proteins globally with unmatched flavor variety and consistent quality at a competitive price.",
  },
  {
    id: "p10", slug: "avvatar-isolate-zero-carb", brandId: "brand-005", categoryId: "cat-002",
    title: "Avvatar Isolate Zero Carb Whey Protein",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDeWeqWAPFlgx_8PXANx_WD-AR-DSxg-7MgKfrWlr5Vw&s",
    rating: 4.7, reviews: 8500, price: 29.92, originalPrice: 36.57,
    website: "HealthKart", delivery: "Free • 2 days", servingSize: "30g",
    ingredients: ["Whey Protein Isolate", "Natural Flavors", "Sucralose"],
    pros: ["100% whey isolate", "Zero carbs", "Made from Indian cow milk"],
    cons: ["Limited flavors", "Slightly premium pricing"],
    bestFor: "Keto diet, low-carb lifestyle",
    warnings: "Not for dairy allergic individuals",
    country: "India", manufacturer: "Parag Milk Foods",
    labTested: true, certificationIds: ["cert-008", "cert-006", "cert-005"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 27, carbs: 0, fat: 0.5, fiber: 0, sugar: 0, calories: 115 },
    healthScore: 94, cleanLabelScore: 90, valueScore: 88,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: false, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["27g Protein", "Zero Carbs", "100% Isolate", "Indian Made"],
    aiSummary: "Premium zero-carb whey isolate made from fresh Indian cow milk, delivering 27g of pure protein with zero carbohydrates.",
  },
  {
    id: "p11", slug: "nakpro-platinum-whey-1kg", brandId: "brand-006", categoryId: "cat-002",
    title: "Nakpro Platinum Whey Protein 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQN9EqEWPcW3zavaM-EgBQhTlkZomvR9bvfxJH7jfzVLA&s=10",
    rating: 4.4, reviews: 6200, price: 14.4, originalPrice: 18.84,
    website: "HealthKart", delivery: "Free • 3 days", servingSize: "30g",
    ingredients: ["Whey Protein Concentrate", "Whey Isolate", "Cocoa", "Sucralose"],
    pros: ["Budget-friendly", "Good protein content", "Wellness brand"],
    cons: ["Basic packaging", "Limited flavor options"],
    bestFor: "Budget-conscious gym-goers",
    warnings: "Contains milk solids",
    country: "India", manufacturer: "Nakpro Health",
    labTested: true, certificationIds: ["cert-008", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 25, carbs: 4, fat: 1.8, fiber: 0, sugar: 1.5, calories: 130 },
    healthScore: 82, cleanLabelScore: 78, valueScore: 95,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["25g Protein", "Budget Friendly", "Affordable Quality", "Indian Brand"],
    aiSummary: "Affordable whey protein that delivers solid nutrition for those starting their fitness journey without breaking the bank.",
  },
  {
    id: "p12", slug: "asitis-whey-1kg", brandId: "brand-007", categoryId: "cat-002",
    title: "AS-IT-IS Nutrition Whey Protein 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkr9QGIqK_iFJrsH_LcdGC9ZdXrGfvovrGsMQT9qk2fA&s=10",
    rating: 4.3, reviews: 15400, price: 12.74, originalPrice: 16.62,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "30g",
    ingredients: ["Whey Protein Concentrate", "Whey Isolate"],
    pros: ["Minimal ingredients", "No artificial flavors", "Clean label"],
    cons: ["Basic taste", "Mixing can be clumpy"],
    bestFor: "Clean eating, minimal ingredient preference",
    warnings: "May contain milk allergens",
    country: "India", manufacturer: "AS-IT-IS Nutrition",
    labTested: true, certificationIds: ["cert-008", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 24, carbs: 3, fat: 1.5, fiber: 0, sugar: 1, calories: 125 },
    healthScore: 85, cleanLabelScore: 95, valueScore: 92,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["24g Protein", "No Artificial Flavors", "Clean Label", "Minimal Ingredients"],
    aiSummary: "A no-nonsense whey protein with zero artificial additives, perfect for those who want clean nutrition without compromise.",
  },
  {
    id: "p13", slug: "gnc-pro-performance-whey", brandId: "brand-008", categoryId: "cat-002",
    title: "GNC Pro Performance 100% Whey Protein 2lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo8P80V5XT-XbXPsFEnCyroRm1tcaRyZWoVxwMC7ZP0g&s=10",
    rating: 4.5, reviews: 9800, price: 38.79, originalPrice: 47.66,
    website: "GNC", delivery: "Free • 2 days", servingSize: "32g",
    ingredients: ["Whey Protein Isolate", "Whey Peptides", "Whey Concentrate", "Cocoa", "Acesulfame Potassium"],
    pros: ["Triple blend of whey", "Good mix of fast + slow release", "Trusted global brand"],
    cons: ["Expensive", "Contains multiple sweeteners"],
    bestFor: "All-day protein supplementation",
    warnings: "Consult physician before use",
    country: "USA", manufacturer: "GNC Holdings",
    labTested: true, certificationIds: ["cert-006", "cert-003"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 24, carbs: 4, fat: 2, fiber: 0.5, sugar: 1, calories: 140 },
    healthScore: 85, cleanLabelScore: 78, valueScore: 78,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["24g Protein", "Triple Blend", "Trusted Brand", "Global Quality"],
    aiSummary: "GNC's signature whey blend combining isolate, peptides, and concentrate for a complete protein profile at every feed.",
  },
  {
    id: "p14", slug: "rule1-100-whey-5lb", brandId: "brand-011", categoryId: "cat-002",
    title: "Rule 1 100% Whey Protein 5lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQexHn3gfzZocnu9ojVuNAaJ79-WXWiH6VXDv_R6ZO6RA&s=10",
    rating: 4.7, reviews: 12500, price: 58.75, originalPrice: 73.16,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "31g",
    ingredients: ["Whey Protein Isolate", "Whey Concentrate", "Maltodextrin", "Cocoa", "Natural Flavors"],
    pros: ["25g protein", "Excellent value for 5lb", "Great taste"],
    cons: ["Large tub size may not suit everyone", "Contains maltodextrin"],
    bestFor: "Serious lifters, bulk buyers",
    warnings: "Contains milk and soy",
    country: "USA", manufacturer: "Rule 1 Proteins",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 25, carbs: 4, fat: 1.5, fiber: 0, sugar: 2, calories: 135 },
    healthScore: 88, cleanLabelScore: 82, valueScore: 92,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["25g Protein", "5lb Value", "Great Taste", "Isolate + Concentrate"],
    aiSummary: "A top-tier whey blend offering 25g of protein in a massive 5lb tub at an unbeatable value for serious athletes.",
  },
  {
    id: "p15", slug: "isopure-zero-carb", brandId: "brand-012", categoryId: "cat-002",
    title: "Isopure Zero Carb Whey Protein Isolate 3lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC2OMaUkRFEXTM7TukXa-lbkQuEUtHUi-rSzfLuuMhvA&s=10",
    rating: 4.8, reviews: 22000, price: 54.31, originalPrice: 66.51,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "31g",
    ingredients: ["Whey Protein Isolate", "Coconut Oil", "Natural Flavors", "Vitamins & Minerals"],
    pros: ["Zero carbs", "Fortified with vitamins", "Pure isolate"],
    cons: ["Expensive per serving", "Some flavors are subtle"],
    bestFor: "Low-carb, keto athletes",
    warnings: "Not for dairy-sensitive individuals",
    country: "USA", manufacturer: "Nature's Best",
    labTested: true, certificationIds: ["cert-001", "cert-006", "cert-003"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 25, carbs: 0, fat: 0.5, fiber: 0, sugar: 0, calories: 106 },
    healthScore: 96, cleanLabelScore: 92, valueScore: 80,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: false, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["25g Protein", "Zero Carbs", "Vitamin Fortified", "Pure Isolate"],
    aiSummary: "The gold standard of zero-carb whey isolates with added vitamins and minerals for the ultimate clean protein experience.",
  },
  {
    id: "p16", slug: "muscleblaze-biozyme-2kg", brandId: "brand-002", categoryId: "cat-002",
    title: "MuscleBlaze Biozyme Performance Whey 2kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyf8QVDxLw1P2WOfuuyswJcgVBLVthiQGUe67GfqYidw&s",
    rating: 4.6, reviews: 21500, price: 33.25, originalPrice: 41.56,
    website: "HealthKart", delivery: "Free • 2 days", servingSize: "33g",
    ingredients: ["Whey Isolate", "Whey Concentrate", "Digezyme", "Lactase", "Cocoa"],
    pros: ["Enzyme technology for better digestion", "Lactose friendly", "Great value"],
    cons: ["Limited flavors", "Slightly higher calories"],
    bestFor: "Athletes with sensitive digestion",
    warnings: "Store in a cool dry place",
    country: "India", manufacturer: "HealthKart",
    labTested: true, certificationIds: ["cert-005", "cert-008", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 25, carbs: 4, fat: 1.5, fiber: 0.5, sugar: 1, calories: 130 },
    healthScore: 90, cleanLabelScore: 85, valueScore: 93,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["25g Protein", "Enzyme Infused", "Lactose Friendly", "Great Value"],
    aiSummary: "Enzyme-infused whey protein designed for superior digestion and absorption with added Digezyme and Lactase for gut comfort.",
  },
  {
    id: "p17", slug: "myprotein-clear-whey-isolate", brandId: "brand-003", categoryId: "cat-002",
    title: "MyProtein Clear Whey Isolate 500g",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFWF98wn9FRjVpjOe6xGCuYiSL4Efgx3t3RAKQQYfUwQ&s=10",
    rating: 4.4, reviews: 12800, price: 21.05, originalPrice: 26.6,
    website: "MyProtein", delivery: "Free • 5 days", servingSize: "25g",
    ingredients: ["Whey Protein Isolate", "Citric Acid", "Natural Flavors", "Sweetener"],
    pros: ["Juicy, refreshing taste", "Like fruit juice", "Low calorie"],
    cons: ["Contains artificial sweeteners", "Smaller serving size"],
    bestFor: "Post-workout refreshment, summer protein",
    warnings: "Contains milk derivatives",
    country: "UK", manufacturer: "The Hut Group",
    labTested: true, certificationIds: ["cert-002", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 20, carbs: 1, fat: 0.1, fiber: 0, sugar: 0.5, calories: 85 },
    healthScore: 90, cleanLabelScore: 85, valueScore: 82,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: false, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["20g Protein", "Juicy Taste", "Low Calorie", "Refreshing"],
    aiSummary: "A unique clear whey isolate that tastes like fruit juice, perfect for those who hate milky shakes but want high-quality protein.",
  },
  {
    id: "p18", slug: "gnc-100-whey-isolate", brandId: "brand-008", categoryId: "cat-002",
    title: "GNC 100% Whey Isolate 2lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmK09hYbdLUxOgivvAl-dS2x1GqfSmd3vAYIMlvwdy-g&s",
    rating: 4.6, reviews: 7500, price: 47.66, originalPrice: 58.75,
    website: "GNC", delivery: "Free • 2 days", servingSize: "28g",
    ingredients: ["Whey Protein Isolate", "Cocoa", "Natural Flavors", "Lecithin"],
    pros: ["Pure isolate", "Low carb", "Trusted brand"],
    cons: ["Premium pricing", "Fewer flavors than competitors"],
    bestFor: "Serious athletes, low-carb dieters",
    warnings: "Contains milk",
    country: "USA", manufacturer: "GNC Holdings",
    labTested: true, certificationIds: ["cert-006", "cert-003"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 24, carbs: 1, fat: 0.5, fiber: 0, sugar: 0, calories: 105 },
    healthScore: 93, cleanLabelScore: 88, valueScore: 78,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["24g Protein", "Pure Isolate", "Low Carb", "Trusted Brand"],
    aiSummary: "Premium whey isolate from GNC with 24g of protein and minimal carbs, ideal for those seeking the purest protein source.",
  },
  {
    id: "p19", slug: "nakpro-whey-isolate-1kg", brandId: "brand-006", categoryId: "cat-002",
    title: "Nakpro Whey Isolate 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHT6ZzixccHwLmZLDqKKN-Nz00H519qbB_-Ok8gUCLfg&s",
    rating: 4.3, reviews: 4800, price: 18.84, originalPrice: 23.82,
    website: "Amazon", delivery: "Free • 3 days", servingSize: "30g",
    ingredients: ["Whey Protein Isolate", "Cocoa Powder", "Sucralose"],
    pros: ["Affordable isolate", "Good macro profile", "Clean ingredients"],
    cons: ["Mixing texture could be better", "Basic taste"],
    bestFor: "Budget-friendly isolate option",
    warnings: "Store in cool dry place",
    country: "India", manufacturer: "Nakpro Health",
    labTested: true, certificationIds: ["cert-008", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 26, carbs: 1.5, fat: 0.8, fiber: 0, sugar: 0.5, calories: 118 },
    healthScore: 88, cleanLabelScore: 85, valueScore: 93,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["26g Protein", "Affordable Isolate", "Clean Profile", "Indian Made"],
    aiSummary: "One of the most affordable whey isolates in India offering 26g of protein per serving without compromising on quality.",
  },
  {
    id: "p20", slug: "rule1-isolate-5lb", brandId: "brand-011", categoryId: "cat-002",
    title: "Rule 1 Isolate 5lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRL0_3DDImUHr_jtNeh1TDk0sDAtHhnCb_zZyakAxWPow&s=10",
    rating: 4.7, reviews: 8900, price: 66.51, originalPrice: 82.03,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "30g",
    ingredients: ["Whey Protein Isolate", "Maltodextrin", "Cocoa", "Natural Flavors"],
    pros: ["27g protein", "Excellent value isolate", "Smooth texture"],
    cons: ["Contains maltodextrin", "Large tub"],
    bestFor: "Isolate seekers on a budget",
    warnings: "Contains milk and soy",
    country: "USA", manufacturer: "Rule 1 Proteins",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 27, carbs: 2, fat: 0.5, fiber: 0, sugar: 0.5, calories: 120 },
    healthScore: 92, cleanLabelScore: 85, valueScore: 90,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["27g Protein", "Pure Isolate", "Value Size", "Smooth Texture"],
    aiSummary: "A premium isolate at an accessible price point, delivering 27g of protein with excellent mixability and taste.",
  },
  {
    id: "p21", slug: "avvatar-whey-concentrate", brandId: "brand-005", categoryId: "cat-002",
    title: "Avvatar Whey Concentrate 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcHWiuRyQkUO6QTcfoP8vaVsFyg_q5K7pgzHnB6bXQdw&s=10",
    rating: 4.5, reviews: 5200, price: 19.94, originalPrice: 24.93,
    website: "HealthKart", delivery: "Free • 2 days", servingSize: "30g",
    ingredients: ["Whey Protein Concentrate", "Natural Flavors"],
    pros: ["Made from fresh milk", "Clean label", "Good value"],
    cons: ["Only concentrate", "Basic packaging"],
    bestFor: "Everyday protein supplementation",
    warnings: "Contains milk solids",
    country: "India", manufacturer: "Parag Milk Foods",
    labTested: true, certificationIds: ["cert-008", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 22, carbs: 4, fat: 2, fiber: 0, sugar: 2, calories: 125 },
    healthScore: 82, cleanLabelScore: 88, valueScore: 90,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["22g Protein", "Fresh Milk Source", "Clean Label", "Indian Made"],
    aiSummary: "A clean whey concentrate made from fresh Indian cow milk with no artificial sweeteners, offering honest nutrition at a fair price.",
  },
  {
    id: "p22", slug: "dymatize-elite-whey-5lb", brandId: "brand-004", categoryId: "cat-002",
    title: "Dymatize Elite Whey Protein 5lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQldFjbbbsmB0FP1UF9MIdQlb0KL4SGNxroeLeMx8hIyA&s=10",
    rating: 4.5, reviews: 16500, price: 49.88, originalPrice: 62.07,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "32g",
    ingredients: ["Whey Protein Isolate", "Whey Concentrate", "Whey Peptides", "Cocoa", "Natural Flavors"],
    pros: ["Triple blend", "Great value 5lb", "Delicious flavors"],
    cons: ["Mix of isolate and concentrate", "Not ideal for strict keto"],
    bestFor: "All-around daily protein",
    warnings: "Contains milk and soy",
    country: "USA", manufacturer: "Dymatize Nutrition",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 23, carbs: 4, fat: 2, fiber: 0, sugar: 1.5, calories: 140 },
    healthScore: 85, cleanLabelScore: 80, valueScore: 90,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["23g Protein", "Triple Blend", "5lb Value", "Great Taste"],
    aiSummary: "A well-rounded triple-blend whey offering exceptional value in the 5lb size with proven quality from a trusted brand.",
  },
  {
    id: "p23", slug: "gnc-whey-protein-4lb", brandId: "brand-008", categoryId: "cat-002",
    title: "GNC Whey Protein 4lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4C_F2KdAwBK6yjCZjbNxcXFeYgEpvh0fXKMdnD_9KtQ&s=10",
    rating: 4.4, reviews: 11200, price: 44.33, originalPrice: 55.42,
    website: "GNC", delivery: "Free • 2 days", servingSize: "30g",
    ingredients: ["Whey Protein Concentrate", "Whey Isolate", "Cocoa", "Sucralose"],
    pros: ["Trusted brand", "Good value per serving", "Available worldwide"],
    cons: ["Contains artificial sweetener", "Not the cleanest label"],
    bestFor: "Mainstream gym-goers",
    warnings: "Contains milk derivatives",
    country: "USA", manufacturer: "GNC Holdings",
    labTested: true, certificationIds: ["cert-006", "cert-003"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 22, carbs: 5, fat: 2.5, fiber: 0.5, sugar: 2, calories: 140 },
    healthScore: 80, cleanLabelScore: 75, valueScore: 85,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["22g Protein", "Trusted Brand", "4lb Value", "Global Availability"],
    aiSummary: "A reliable, widely available whey protein from a globally trusted retailer offering consistent quality at a mid-range price.",
  },
  {
    id: "p24", slug: "asitis-isolate-1kg", brandId: "brand-007", categoryId: "cat-002",
    title: "AS-IT-IS Nutrition Whey Isolate 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCM-sr9nnUZotZ84hqAnAubrXV7n8J8BR9Aoa7WYPajA&s",
    rating: 4.4, reviews: 9200, price: 17.73, originalPrice: 22.16,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "30g",
    ingredients: ["Whey Protein Isolate", "Soy Lecithin"],
    pros: ["Minimalist label", "No artificial anything", "Great pricing"],
    cons: ["Basic unflavored taste", "Mixing takes effort"],
    bestFor: "Clean eaters, minimalists",
    warnings: "Contains milk and soy",
    country: "India", manufacturer: "AS-IT-IS Nutrition",
    labTested: true, certificationIds: ["cert-008", "cert-005"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 26, carbs: 1, fat: 0.5, fiber: 0, sugar: 0, calories: 112 },
    healthScore: 95, cleanLabelScore: 98, valueScore: 94,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["26g Protein", "Minimal Ingredients", "No Additives", "Great Price"],
    aiSummary: "The ultimate clean-label whey isolate with just two ingredients, offering 26g of protein with nothing artificial.",
  },
  {
    id: "p25", slug: "optimum-gold-standard-10lb", brandId: "brand-001", categoryId: "cat-002",
    title: "Gold Standard 100% Whey Protein 10lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeqYFDg6086uIDJM3XKxwjFDT558aKwX-xnIAOK0GJ9g&s=10",
    rating: 4.9, reviews: 35000, price: 110.85, originalPrice: 138.57,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "30g",
    ingredients: ["Whey Protein Isolate", "Whey Concentrate", "Whey Peptides", "Cocoa", "Acesulfame Potassium"],
    pros: ["Best-selling whey globally", "Consistent quality", "Great value per serving"],
    cons: ["Large tub size", "Contains artificial sweeteners"],
    bestFor: "Heavy users, bulk buyers",
    warnings: "Not for those allergic to milk",
    country: "USA", manufacturer: "Glanbia Performance Nutrition",
    labTested: true, certificationIds: ["cert-001", "cert-006", "cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 24, carbs: 3, fat: 1, fiber: 0, sugar: 1, calories: 120 },
    healthScore: 90, cleanLabelScore: 85, valueScore: 94,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["24g Protein", "World's Best Seller", "10lb Value", "Consistent Quality"],
    aiSummary: "The world's best-selling whey protein for good reason — consistent quality, excellent taste, and unbeatable bulk value.",
  },
  {
    id: "p26", slug: "herbalife-formula1-whey", brandId: "brand-046", categoryId: "cat-002",
    title: "Herbalife Formula 1 Whey Protein Shake Mix",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFSNXvBkLXGfGUCP8613XQVV5vWWgxCYjI8D-Pvql5UQ&s=10",
    rating: 4.3, reviews: 28000, price: 27.71, originalPrice: 33.25,
    website: "Herbalife", delivery: "Free • 3 days", servingSize: "25g",
    ingredients: ["Whey Protein Concentrate", "Soy Protein Isolate", "Fructose", "Vitamins & Minerals"],
    pros: ["Meal replacement option", "Fortified with vitamins", "Global brand"],
    cons: ["Contains soy", "Added sugars", "Multi-level marketing model"],
    bestFor: "Weight management, meal replacement",
    warnings: "Not a complete meal replacement",
    country: "USA", manufacturer: "Herbalife Nutrition",
    labTested: true, certificationIds: ["cert-006", "cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 18, carbs: 9, fat: 2.5, fiber: 3, sugar: 5, calories: 140 },
    healthScore: 75, cleanLabelScore: 65, valueScore: 70,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["Meal Replacement", "Vitamin Fortified", "Global Brand", "Weight Management"],
    aiSummary: "A popular meal replacement shake with added vitamins, suitable for weight management but with higher sugar content.",
  },
  {
    id: "p27", slug: "labrada-whey-2lb", brandId: "brand-013", categoryId: "cat-002",
    title: "Labrada Whey Protein Isolate 2lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS026qAx9aFsKlXunYLVI3DBmhRrMeuqC6mdLy7Q9rMIg&s=10",
    rating: 4.5, reviews: 4200, price: 38.79, originalPrice: 47.66,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "30g",
    ingredients: ["Whey Protein Isolate", "Cocoa", "Natural Flavors", "Lecithin"],
    pros: ["High quality isolate", "Great taste", "Respected brand"],
    cons: ["Premium pricing", "Limited availability in India"],
    bestFor: "Serious bodybuilders",
    warnings: "Contains milk",
    country: "USA", manufacturer: "Labrada Nutrition",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 24, carbs: 1, fat: 0.5, fiber: 0, sugar: 0, calories: 108 },
    healthScore: 93, cleanLabelScore: 90, valueScore: 80,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: false, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["24g Protein", "Pure Isolate", "Great Taste", "Respected Brand"],
    aiSummary: "A premium whey isolate from a respected bodybuilding brand, combining great taste with clean macros and proven quality.",
  },
  {
    id: "p28", slug: "ultimate-nutrition-whey", brandId: "brand-016", categoryId: "cat-002",
    title: "Ultimate Nutrition Whey Protein 2lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSO4SBpdqRVDTXu-6z2qCAbt0JejZUxwB6r2rSB8pLITg&s=10",
    rating: 4.3, reviews: 6800, price: 27.71, originalPrice: 34.36,
    website: "Amazon", delivery: "Free • 3 days", servingSize: "30g",
    ingredients: ["Whey Protein Concentrate", "Whey Isolate", "Cocoa", "Sucralose"],
    pros: ["Decades of trust", "Affordable", "Decent macros"],
    cons: ["Not the best mixability", "Basic formulation"],
    bestFor: "Budget-conscious buyers",
    warnings: "Contains milk solids",
    country: "USA", manufacturer: "Ultimate Nutrition",
    labTested: true, certificationIds: ["cert-006", "cert-003"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 22, carbs: 4, fat: 2, fiber: 0, sugar: 1.5, calories: 130 },
    healthScore: 80, cleanLabelScore: 75, valueScore: 85,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["22g Protein", "Affordable", "Long-Standing Brand", "Decent Macros"],
    aiSummary: "A budget-friendly whey from a brand with decades of history in sports nutrition, offering reliable quality at a modest price.",
  },
  {
    id: "p29", slug: "rule1-100-whey-2lb", brandId: "brand-011", categoryId: "cat-002",
    title: "Rule 1 100% Whey Protein 2lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTtIBusW6nJYuVnu2YjmAoDyPfxvpn_KuRlr4c0b5oAw&s=10",
    rating: 4.6, reviews: 5400, price: 27.71, originalPrice: 34.36,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "31g",
    ingredients: ["Whey Protein Isolate", "Whey Concentrate", "Cocoa", "Natural Flavors"],
    pros: ["25g protein", "Excellent taste", "Good intro size"],
    cons: ["Slightly more expensive per serving than 5lb"],
    bestFor: "First-time buyers, travel",
    warnings: "Contains milk and soy",
    country: "USA", manufacturer: "Rule 1 Proteins",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 25, carbs: 4, fat: 1.5, fiber: 0, sugar: 2, calories: 135 },
    healthScore: 88, cleanLabelScore: 82, valueScore: 88,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["25g Protein", "Great Taste", "Intro Size", "Premium Quality"],
    aiSummary: "A fantastic entry-size tub of Rule 1's acclaimed whey blend, perfect for trying the brand before committing to the 5lb.",
  },
  {
    id: "p30", slug: "bsn-syntha-6-5lb", brandId: "brand-014", categoryId: "cat-002",
    title: "BSN Syntha-6 Whey Protein 5lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMbNLvK2IG47XxU0KMGUukZA3X4EDbcPjSJbfMpaORnA&s=10",
    rating: 4.6, reviews: 19500, price: 53.2, originalPrice: 66.51,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "47g",
    ingredients: ["Whey Isolate", "Whey Concentrate", "Milk Protein Concentrate", "Egg Albumin", "Cocoa", "Maltodextrin"],
    pros: ["Multi-source protein", "Amazing taste", "Thick milkshake texture"],
    cons: ["Higher calories", "More carbs", "Premium price"],
    bestFor: "Taste seekers, meal replacement",
    warnings: "Contains milk and egg",
    country: "USA", manufacturer: "BSN",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 22, carbs: 15, fat: 5, fiber: 2, sugar: 4, calories: 200 },
    healthScore: 78, cleanLabelScore: 72, valueScore: 82,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: false, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: true, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["22g Protein", "Milkshake Taste", "Multi-Source", "Premium Blend"],
    aiSummary: "Famous for its incredible taste and thick milkshake-like texture, Syntha-6 is a premium multi-source protein blend.",
  },
  {
    id: "p31", slug: "fuel-one-whey-1kg", brandId: "brand-017", categoryId: "cat-002",
    title: "Fuel One Whey Protein 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQynekh8SitdFqXhx8grfsvOUQnrE-hWNxz9RLwN7hpvg&s=10",
    rating: 4.2, reviews: 3800, price: 12.18, originalPrice: 15.51,
    website: "HealthKart", delivery: "Free • 3 days", servingSize: "30g",
    ingredients: ["Whey Protein Concentrate", "Cocoa", "Sucralose"],
    pros: ["Very affordable", "Decent protein content", "Good entry-level option"],
    cons: ["Basic quality", "More carbs and fat", "Simple packaging"],
    bestFor: "Students, beginners on tight budget",
    warnings: "Contains milk solids",
    country: "India", manufacturer: "Fuel One",
    labTested: true, certificationIds: ["cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 22, carbs: 6, fat: 2.5, fiber: 0.5, sugar: 2, calories: 140 },
    healthScore: 72, cleanLabelScore: 68, valueScore: 92,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: false, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["22g Protein", "Budget Friendly", "Entry Level", "Indian Brand"],
    aiSummary: "One of the most affordable whey proteins in India, offering solid value for beginners on a tight budget.",
  },
  {
    id: "p32", slug: "carbamide-forte-whey", brandId: "brand-018", categoryId: "cat-002",
    title: "Carbamide Forte Whey Protein 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTo1xhrqi6bz24mo1FoEQMIkpiyPEmI7wiACTbAcg_E5w&s=10",
    rating: 4.1, reviews: 7200, price: 11.08, originalPrice: 14.4,
    website: "Amazon", delivery: "Free • 3 days", servingSize: "30g",
    ingredients: ["Whey Protein Concentrate", "Cocoa", "Sucralose", "Artificial Flavors"],
    pros: ["Lowest price in category", "Widely available", "Good for beginners"],
    cons: ["Lower protein percentage", "More additives", "Basic quality"],
    bestFor: "Extreme budget buyers",
    warnings: "Store in cool dry place",
    country: "India", manufacturer: "Carbamide Forte",
    labTested: true, certificationIds: ["cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 20, carbs: 7, fat: 3, fiber: 0.5, sugar: 2.5, calories: 145 },
    healthScore: 68, cleanLabelScore: 60, valueScore: 88,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["20g Protein", "Lowest Price", "Widely Available", "Beginner Option"],
    aiSummary: "The most budget-friendly option in the whey protein category, suitable for absolute beginners with very tight budgets.",
  },
  {
    id: "p33", slug: "kevin-levrone-whey", brandId: "brand-015", categoryId: "cat-002",
    title: "Kevin Levrone Signature Whey 2lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRENVSBgb0Yect1bNzq-cLw7tl26ydnF9NSXHR6oBmVA&s=10",
    rating: 4.6, reviews: 3100, price: 33.25, originalPrice: 42.12,
    website: "Amazon", delivery: "Free • 3 days", servingSize: "32g",
    ingredients: ["Whey Protein Isolate", "Whey Concentrate", "Cocoa", "Natural Flavors"],
    pros: ["Pro athlete formulated", "High quality", "Great flavor"],
    cons: ["Limited availability", "Premium pricing"],
    bestFor: "Bodybuilding enthusiasts",
    warnings: "Contains milk",
    country: "USA", manufacturer: "Kevin Levrone",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 24, carbs: 3, fat: 1, fiber: 0, sugar: 1, calories: 125 },
    healthScore: 90, cleanLabelScore: 86, valueScore: 80,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["24g Protein", "Athlete Formulated", "Great Flavor", "Premium Quality"],
    aiSummary: "Developed by legendary bodybuilder Kevin Levrone, this whey delivers premium quality with an athlete-tested formula.",
  },
  {
    id: "p34", slug: "muscleblaze-whey-1kg", brandId: "brand-002", categoryId: "cat-002",
    title: "MuscleBlaze Whey Protein 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8qbScn0rkp4lmnpmuRJ6OoKue-JaJuyc1amoCNnJNdQ&s=10",
    rating: 4.5, reviews: 12500, price: 15.51, originalPrice: 19.39,
    website: "HealthKart", delivery: "Free • 2 days", servingSize: "30g",
    ingredients: ["Whey Protein Concentrate", "Whey Isolate", "Cocoa", "Sucralose"],
    pros: ["Affordable entry", "Good brand reputation", "Decent quality"],
    cons: ["Basic formulation", "Contains sweeteners"],
    bestFor: "Everyday gym-goers",
    warnings: "Not for lactose intolerant",
    country: "India", manufacturer: "HealthKart",
    labTested: true, certificationIds: ["cert-005", "cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 23, carbs: 5, fat: 1.8, fiber: 0, sugar: 1.5, calories: 130 },
    healthScore: 82, cleanLabelScore: 76, valueScore: 90,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["23g Protein", "Affordable", "Trusted Brand", "Good Quality"],
    aiSummary: "A reliable, affordable whey protein from India's leading sports nutrition brand, perfect for everyday use.",
  },
  {
    id: "p35", slug: "myprotein-whey-isolate-1kg", brandId: "brand-003", categoryId: "cat-002",
    title: "MyProtein Whey Isolate 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSH-oJurR_ScMFsRKn3ISFixMawMGpD-2MQTFVtq1nOCQ&s=10",
    rating: 4.6, reviews: 9800, price: 36.57, originalPrice: 45.44,
    website: "MyProtein", delivery: "Free • 5 days", servingSize: "25g",
    ingredients: ["Whey Protein Isolate", "Natural Flavors", "Lecithin"],
    pros: ["High protein content", "Low fat and carbs", "Clean label"],
    cons: ["International shipping", "Premium pricing"],
    bestFor: "Protein purification, low-carb diet",
    warnings: "Contains milk",
    country: "UK", manufacturer: "The Hut Group",
    labTested: true, certificationIds: ["cert-002", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 23, carbs: 1, fat: 0.3, fiber: 0, sugar: 0.5, calories: 98 },
    healthScore: 94, cleanLabelScore: 90, valueScore: 82,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["23g Protein", "Ultra-Low Fat", "Clean Label", "Premium Isolate"],
    aiSummary: "A clean, premium whey isolate with exceptional macros — 23g protein with virtually no fat or carbs.",
  },
  {
    id: "p36", slug: "optimum-gold-standard-2lb", brandId: "brand-001", categoryId: "cat-002",
    title: "Gold Standard 100% Whey Protein 2lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRC-XepzvYTHpu25n2xi_ZYG5tBZCmVLZb8H2FDA_oDw&s=10",
    rating: 4.8, reviews: 12480, price: 36.57, originalPrice: 46.55,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "30g",
    ingredients: ["Whey Protein Isolate", "Whey Concentrate", "Whey Peptides", "Cocoa", "Lecithin", "Natural Flavors"],
    pros: ["24g high-quality protein", "Low sugar", "Fast absorption", "Informed Choice tested"],
    cons: ["Contains artificial sweeteners", "Premium price"],
    bestFor: "Post-workout recovery, muscle building",
    warnings: "Not for those with dairy allergies",
    country: "USA", manufacturer: "Glanbia Performance Nutrition",
    labTested: true, certificationIds: ["cert-001", "cert-006", "cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 24, carbs: 3, fat: 1, fiber: 0, sugar: 1, calories: 120 },
    healthScore: 93, cleanLabelScore: 90, valueScore: 87,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["24g Protein", "Low Sugar", "Informed Choice Certified", "Fast Absorption"],
    aiSummary: "Premium whey protein with excellent amino acid profile, minimal fillers, and ideal for lean muscle growth.",
  },
  {
    id: "p37", slug: "muscleblaze-biozyme-1kg", brandId: "brand-002", categoryId: "cat-002",
    title: "MuscleBlaze Biozyme Whey 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNyZMcPvEjxyUKgInsHrXbUROvW20jY-hjVrwXeoiWYg&s=10",
    rating: 4.5, reviews: 10800, price: 18.28, originalPrice: 22.72,
    website: "HealthKart", delivery: "Free • 2 days", servingSize: "33g",
    ingredients: ["Whey Isolate", "Whey Concentrate", "Digezyme", "Lactase"],
    pros: ["Digestive enzymes included", "Good value", "Effective"],
    cons: ["Limited flavor options", "Medium protein content"],
    bestFor: "Digestion-conscious athletes",
    warnings: "Consult physician if pregnant",
    country: "India", manufacturer: "HealthKart",
    labTested: true, certificationIds: ["cert-005", "cert-008", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 25, carbs: 2.5, fat: 1.2, fiber: 0.5, sugar: 0.8, calories: 125 },
    healthScore: 90, cleanLabelScore: 85, valueScore: 92,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["25g Protein", "Digestive Enzymes", "Lactose Friendly", "Great Value"],
    aiSummary: "Enzyme-infused whey protein designed for superior digestion and absorption, ideal for those with mild lactose sensitivity.",
  },
  {
    id: "p38", slug: "myprotein-impact-whey-1kg", brandId: "brand-003", categoryId: "cat-002",
    title: "MyProtein Impact Whey Protein 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRy5sM8PZooAFMujKoNFuMxvGOgopFXeEgfD0YgBmeOuw&s=10",
    rating: 4.5, reviews: 15200, price: 27.71, originalPrice: 34.36,
    website: "MyProtein", delivery: "Free • 5 days", servingSize: "25g",
    ingredients: ["Whey Protein Concentrate", "Whey Isolate", "Natural Flavors", "Lecithin"],
    pros: ["Great value", "60+ flavors", "Global brand"],
    cons: ["Contains concentrate", "Shipping time"],
    bestFor: "Daily protein needs",
    warnings: "Contains milk",
    country: "UK", manufacturer: "The Hut Group",
    labTested: true, certificationIds: ["cert-002", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 21, carbs: 3, fat: 1.9, fiber: 0.3, sugar: 1, calories: 115 },
    healthScore: 87, cleanLabelScore: 85, valueScore: 90,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["21g Protein", "60+ Flavors", "Great Value", "Global Brand"],
    aiSummary: "Popular whey with unmatched flavor variety and consistent quality at a competitive price point.",
  },
  {
    id: "p39", slug: "dymatize-iso100-2lb", brandId: "brand-004", categoryId: "cat-002",
    title: "Dymatize ISO100 Hydrolyzed Whey 2lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJN_46dIU_Sli1zKUb3Y5XUo9Na43rmf4so7HBK90PGA&s=10",
    rating: 4.8, reviews: 14500, price: 38.79, originalPrice: 47.66,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "29g",
    ingredients: ["Hydrolyzed Whey Protein Isolate", "Cocoa", "Natural Flavors", "Lecithin"],
    pros: ["25g protein", "Rapid absorption", "Zero sugar"],
    cons: ["Very expensive", "Limited flavors"],
    bestFor: "Post-workout window, serious athletes",
    warnings: "Contains milk",
    country: "USA", manufacturer: "Dymatize Nutrition",
    labTested: true, certificationIds: ["cert-001", "cert-006", "cert-003"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 25, carbs: 1, fat: 0.5, fiber: 0, sugar: 0, calories: 110 },
    healthScore: 95, cleanLabelScore: 93, valueScore: 82,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["25g Protein", "Zero Sugar", "Hydrolyzed", "Fast Absorption"],
    aiSummary: "A premium hydrolyzed whey isolate with rapid absorption, 25g protein, and zero sugar. Top choice for serious athletes.",
  },
  {
    id: "p40", slug: "ult-nutrition-prostar-whey", brandId: "brand-016", categoryId: "cat-002",
    title: "Ultimate Nutrition ProStar Whey 5lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3Y64HBDq1SM8nsXGNXCQsQ5f_1Ry6w4idMaGVSuPAww&s",
    rating: 4.4, reviews: 8900, price: 49.88, originalPrice: 62.07,
    website: "Amazon", delivery: "Free • 3 days", servingSize: "30g",
    ingredients: ["Whey Protein Isolate", "Whey Concentrate", "Cocoa", "Acesulfame Potassium"],
    pros: ["Affordable for 5lb", "Decent quality", "Well-known brand"],
    cons: ["Contains artificial sweeteners", "Not the best taste"],
    bestFor: "Value-conscious buyers",
    warnings: "Contains milk and soy",
    country: "USA", manufacturer: "Ultimate Nutrition",
    labTested: true, certificationIds: ["cert-006", "cert-003"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 22, carbs: 4, fat: 1.8, fiber: 0, sugar: 1, calories: 130 },
    healthScore: 82, cleanLabelScore: 75, valueScore: 88,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["22g Protein", "5lb Value", "Trusted Brand", "Affordable"],
    aiSummary: "A solid value option in the 5lb category from a brand with decades of history in sports nutrition.",
  },
  {
    id: "p41", slug: "bsn-syntha-6-2lb", brandId: "brand-014", categoryId: "cat-002",
    title: "BSN Syntha-6 Whey Protein 2lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST28HK23zACv90uHgI3egE_9uqa8ptnpUEMlegwcyG9g&s=10",
    rating: 4.5, reviews: 11200, price: 29.92, originalPrice: 37.68,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "47g",
    ingredients: ["Whey Isolate", "Whey Concentrate", "Milk Protein Concentrate", "Egg Albumin", "Cocoa"],
    pros: ["Premium taste", "Multi-source", "Thick texture"],
    cons: ["Higher calories", "More carbs"],
    bestFor: "Taste-focused users",
    warnings: "Contains milk, egg, soy",
    country: "USA", manufacturer: "BSN",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 22, carbs: 15, fat: 5, fiber: 2, sugar: 4, calories: 200 },
    healthScore: 78, cleanLabelScore: 72, valueScore: 80,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: false, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: true, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["22g Protein", "Milkshake Taste", "Multi-Source", "Premium Quality"],
    aiSummary: "The legendary Syntha-6 in a convenient 2lb size, famous for its incredible taste and multi-source protein matrix.",
  },
  {
    id: "p42", slug: "rule1-100-whey-10lb", brandId: "brand-011", categoryId: "cat-002",
    title: "Rule 1 100% Whey Protein 10lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaINJJcq4e1t4N4BsAwwV9RuCjsu-PcW4bX81V7Agd2w&s=10",
    rating: 4.7, reviews: 7800, price: 99.77, originalPrice: 121.94,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "31g",
    ingredients: ["Whey Protein Isolate", "Whey Concentrate", "Cocoa", "Natural Flavors"],
    pros: ["25g protein", "Best value per serving", "Excellent taste"],
    cons: ["Very large tub", "Storage space needed"],
    bestFor: "Heavy users, bulk buyers",
    warnings: "Contains milk and soy",
    country: "USA", manufacturer: "Rule 1 Proteins",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 25, carbs: 4, fat: 1.5, fiber: 0, sugar: 2, calories: 135 },
    healthScore: 88, cleanLabelScore: 82, valueScore: 95,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["25g Protein", "10lb Value", "Best Value", "Premium Quality"],
    aiSummary: "The ultimate value proposition — 25g of premium whey protein in a massive 10lb tub at the lowest cost per serving.",
  },
  {
    id: "p43", slug: "muscleblaze-raw-whey", brandId: "brand-002", categoryId: "cat-002",
    title: "MuscleBlaze Raw Whey Protein 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs7H4ErjlAHtkzjyVrrl7O4D-TQgPB675ViAeKKOHhOA&s",
    rating: 4.4, reviews: 5600, price: 13.85, originalPrice: 17.17,
    website: "HealthKart", delivery: "Free • 2 days", servingSize: "30g",
    ingredients: ["Whey Protein Concentrate"],
    pros: ["Unflavored, no additives", "Clean label", "Budget-friendly"],
    cons: ["No taste", "Can be clumpy"],
    bestFor: "Cooking, smoothies, clean eaters",
    warnings: "Contains milk solids",
    country: "India", manufacturer: "HealthKart",
    labTested: true, certificationIds: ["cert-005", "cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 23, carbs: 4, fat: 1.5, fiber: 0, sugar: 1.5, calories: 125 },
    healthScore: 85, cleanLabelScore: 96, valueScore: 92,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["23g Protein", "No Additives", "Unflavored", "Versatile"],
    aiSummary: "A pure, unflavored whey concentrate with no additives whatsoever, perfect for cooking, baking, or custom flavoring.",
  },
  {
    id: "p44", slug: "dymatize-elite-whey-2lb", brandId: "brand-004", categoryId: "cat-002",
    title: "Dymatize Elite Whey Protein 2lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR62WgzKuRozKC1Hl7W_Jz0tLH5hbEMZKMKi8EgH2dkfA&s",
    rating: 4.4, reviews: 7200, price: 25.49, originalPrice: 32.14,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "32g",
    ingredients: ["Whey Isolate", "Whey Concentrate", "Whey Peptides", "Cocoa", "Natural Flavors"],
    pros: ["Triple blend", "Good taste", "Affordable"],
    cons: ["Contains artificial sweeteners", "Not the cleanest"],
    bestFor: "Everyday protein needs",
    warnings: "Contains milk",
    country: "USA", manufacturer: "Dymatize Nutrition",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 23, carbs: 4, fat: 2, fiber: 0, sugar: 1.5, calories: 140 },
    healthScore: 85, cleanLabelScore: 80, valueScore: 85,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["23g Protein", "Triple Blend", "Good Taste", "Affordable"],
    aiSummary: "A well-rounded whey blend from Dymatize offering solid macros and great taste at a reasonable price point.",
  },
  {
    id: "p45", slug: "avvatar-whey-isolate-1kg", brandId: "brand-005", categoryId: "cat-002",
    title: "Avvatar Whey Isolate 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsd3m7XJpXQvSEftuQOrjMSyad7nax7b8uS36YO6wG4A&s",
    rating: 4.6, reviews: 4100, price: 24.38, originalPrice: 30.48,
    website: "HealthKart", delivery: "Free • 2 days", servingSize: "30g",
    ingredients: ["Whey Protein Isolate", "Natural Flavors"],
    pros: ["Pure isolate", "Indian fresh milk", "No artificial sweeteners"],
    cons: ["Premium pricing", "Limited flavors"],
    bestFor: "Premium isolate seekers",
    warnings: "Contains milk",
    country: "India", manufacturer: "Parag Milk Foods",
    labTested: true, certificationIds: ["cert-008", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 26, carbs: 1, fat: 0.5, fiber: 0, sugar: 0, calories: 115 },
    healthScore: 94, cleanLabelScore: 92, valueScore: 86,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["26g Protein", "Pure Isolate", "Fresh Milk", "No Sweeteners"],
    aiSummary: "A premium Indian whey isolate made from fresh cow milk with no artificial sweeteners, delivering 26g clean protein.",
  },
  {
    id: "p46", slug: "gnc-100-whey-4lb", brandId: "brand-008", categoryId: "cat-002",
    title: "GNC 100% Whey Protein 4lb",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtAGgQ49XOcrzFzv4w0OauiJF_Yeuz2WVpFAlCM43CWw&s=10",
    rating: 4.5, reviews: 6300, price: 50.99, originalPrice: 63.18,
    website: "GNC", delivery: "Free • 2 days", servingSize: "29g",
    ingredients: ["Whey Protein Isolate", "Whey Concentrate", "Cocoa", "Sucralose"],
    pros: ["High quality", "Good value per serving", "Trusted brand"],
    cons: ["Expensive upfront", "Premium pricing"],
    bestFor: "Quality-conscious users",
    warnings: "Contains milk derivatives",
    country: "USA", manufacturer: "GNC Holdings",
    labTested: true, certificationIds: ["cert-006", "cert-003", "cert-001"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 24, carbs: 2, fat: 1, fiber: 0, sugar: 0.5, calories: 115 },
    healthScore: 90, cleanLabelScore: 85, valueScore: 82,
    dietaryInfo: { vegetarian: true, vegan: false, glutenFree: true, lactoseFree: false },
    ingredientFlags: { containsArtificialSweetener: true, containsSoy: true, containsGluten: false, containsLactose: true, containsSugarAlcohol: false },
    highlights: ["24g Protein", "High Quality", "Trusted Brand", "Great Taste"],
    aiSummary: "GNC's premium whey protein blend offering high-quality nutrition with 24g of protein per serving from a globally trusted retailer.",
  },
  // ─── CREATINE (20 products) ───
  {
    id: "p47", slug: "optimum-creatine-300g", brandId: "brand-001", categoryId: "cat-003",
    title: "Micronized Creatine Monohydrate 300g",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxTr0DoP2wQvNInaPZkIohuU3hvgQ3PcUB_bxWWG_G1Q&s=10",
    rating: 4.9, reviews: 22100, price: 17.73, originalPrice: 22.16,
    website: "Amazon", delivery: "Free • 1 day", servingSize: "5g",
    ingredients: ["Creatine Monohydrate (Creapure®)"],
    pros: ["Pure Creapure®", "Micronized", "Unflavored versatility"],
    cons: ["No taste masking"],
    bestFor: "Strength and power athletes",
    warnings: "Stay well hydrated",
    country: "USA", manufacturer: "Glanbia",
    labTested: true, certificationIds: ["cert-004", "cert-001"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 98, cleanLabelScore: 98, valueScore: 95,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Creapure® Certified", "Micronized", "Unflavored", "0 Calories"],
    aiSummary: "The gold standard of creatine — pure, micronized, and third-party tested for maximum strength and power output.",
  },
  {
    id: "p48", slug: "muscleblaze-creatine-250g", brandId: "brand-002", categoryId: "cat-003",
    title: "MuscleBlaze Creatine Monohydrate 250g",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2DYw2SnKtgPeC86cUdlNWmSkpPQYK4ND9yyUUqEHTnQ&s=10",
    rating: 4.5, reviews: 14500, price: 7.75, originalPrice: 9.97,
    website: "HealthKart", delivery: "Free • 2 days", servingSize: "5g",
    ingredients: ["Creatine Monohydrate"],
    pros: ["Affordable", "Micronized", "Good quality"],
    cons: ["Not Creapure®, but tested"],
    bestFor: "General strength training",
    warnings: "Stay hydrated",
    country: "India", manufacturer: "HealthKart",
    labTested: true, certificationIds: ["cert-005", "cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 92, cleanLabelScore: 90, valueScore: 97,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Micronized", "Affordable", "Lab Tested", "Indian Brand"],
    aiSummary: "A budget-friendly, lab-tested creatine monohydrate that delivers the same proven performance as premium imports.",
  },
  {
    id: "p49", slug: "dymatize-creatine-300g", brandId: "brand-004", categoryId: "cat-003",
    title: "Dymatize Creatine Monohydrate 300g",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMoWTx6aQXm6kyabhpMBVvqll0O2LLUo1Tf98HWFS4zA&s=10",
    rating: 4.7, reviews: 8900, price: 16.62, originalPrice: 21.05,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "5g",
    ingredients: ["Creatine Monohydrate"],
    pros: ["Pure micronized", "Trusted brand", "Good value"],
    cons: ["Standard creatine, nothing special"],
    bestFor: "Strength athletes",
    warnings: "Stay well hydrated",
    country: "USA", manufacturer: "Dymatize Nutrition",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 95, cleanLabelScore: 95, valueScore: 90,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Micronized", "Pure", "Trusted Brand", "0 Calories"],
    aiSummary: "A high-quality micronized creatine from a trusted brand, offering pure monohydrate at a competitive price.",
  },
  {
    id: "p50", slug: "asitis-creatine-500g", brandId: "brand-007", categoryId: "cat-003",
    title: "AS-IT-IS Creatine Monohydrate 500g",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKm2jvbcUFhrg3Mt62Bu1wQTZ1L9duk7hVgQ8yGZkysQ&s",
    rating: 4.4, reviews: 11200, price: 9.97, originalPrice: 12.74,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "5g",
    ingredients: ["Creatine Monohydrate"],
    pros: ["Minimal ingredients", "Great value 500g", "Unflavored"],
    cons: ["Basic packaging", "No micronized label"],
    bestFor: "Value-conscious buyers",
    warnings: "Consume with plenty of water",
    country: "India", manufacturer: "AS-IT-IS Nutrition",
    labTested: true, certificationIds: ["cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 93, cleanLabelScore: 98, valueScore: 96,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["500g Value", "Pure Creatine", "Minimalist Label", "Great Price"],
    aiSummary: "A no-frills 500g creatine monohydrate with nothing added — just pure creatine at the lowest cost per serving.",
  },
  {
    id: "p51", slug: "myprotein-creatine-500g", brandId: "brand-003", categoryId: "cat-003",
    title: "MyProtein Creatine Monohydrate 500g",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQg5TiRIA5fQUK_ZCUalrHVy-G2SarS5iWY7Nzuwh67iw&s=10",
    rating: 4.6, reviews: 12500, price: 19.94, originalPrice: 24.38,
    website: "MyProtein", delivery: "Free • 5 days", servingSize: "5g",
    ingredients: ["Creatine Monohydrate"],
    pros: ["Pure monohydrate", "Good value", "Global brand"],
    cons: ["International shipping"],
    bestFor: "Quality creatine needs",
    warnings: "Stay hydrated",
    country: "UK", manufacturer: "The Hut Group",
    labTested: true, certificationIds: ["cert-002", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 95, cleanLabelScore: 95, valueScore: 90,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["500g Value", "Pure Monohydrate", "Global Brand", "0 Calories"],
    aiSummary: "A pure, high-quality creatine monohydrate from a global leader, offering proven performance at a fair price.",
  },
  {
    id: "p52", slug: "rule1-creatine-300g", brandId: "brand-011", categoryId: "cat-003",
    title: "Rule 1 Creatine Monohydrate 300g",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZ-XjV7o6vrZ7xzc4rI0rNwDr7qBMc2ByndNO32iBNbA&s=10",
    rating: 4.7, reviews: 3400, price: 14.4, originalPrice: 17.73,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "5g",
    ingredients: ["Creatine Monohydrate"],
    pros: ["Pure creatine", "Great value", "Trusted brand"],
    cons: ["Standard no frills"],
    bestFor: "Strength and power",
    warnings: "Drink plenty of water",
    country: "USA", manufacturer: "Rule 1 Proteins",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 95, cleanLabelScore: 95, valueScore: 92,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Pure Creatine", "Great Value", "Trusted Brand", "0 Calories"],
    aiSummary: "A pure, no-frills creatine monohydrate from a rapidly growing brand, delivering proven strength benefits.",
  },
  {
    id: "p53", slug: "nakpro-creatine-250g", brandId: "brand-006", categoryId: "cat-003",
    title: "Nakpro Creatine Monohydrate 250g",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzltrMpB_WKpOcQl9BG9QicpwlyxgsJPWqnIOagYx3LA&s=10",
    rating: 4.3, reviews: 6200, price: 6.09, originalPrice: 7.75,
    website: "Amazon", delivery: "Free • 3 days", servingSize: "5g",
    ingredients: ["Creatine Monohydrate"],
    pros: ["Lowest price", "Good quality", "Indian brand"],
    cons: ["Basic packaging", "Not micronized"],
    bestFor: "Extreme budget buyers",
    warnings: "Stay hydrated during use",
    country: "India", manufacturer: "Nakpro Health",
    labTested: true, certificationIds: ["cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 88, cleanLabelScore: 90, valueScore: 98,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Lowest Price", "Pure Creatine", "Indian Brand", "Good Quality"],
    aiSummary: "The most affordable creatine monohydrate in India, offering proven strength benefits at an unbeatable price.",
  },
  {
    id: "p54", slug: "carbamide-forte-creatine", brandId: "brand-018", categoryId: "cat-003",
    title: "Carbamide Forte Creatine Monohydrate 250g",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2dSijm1jSWvo24L1cvOPDlZzvTjY8LzH2pa3VWlDwfg&s=10",
    rating: 4.2, reviews: 4800, price: 5.53, originalPrice: 7.2,
    website: "Amazon", delivery: "Free • 3 days", servingSize: "5g",
    ingredients: ["Creatine Monohydrate"],
    pros: ["Extremely affordable", "Widely available"],
    cons: ["Basic quality", "Powder not micronized"],
    bestFor: "Absolute beginners",
    warnings: "Drink sufficient water",
    country: "India", manufacturer: "Carbamide Forte",
    labTested: true, certificationIds: ["cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 82, cleanLabelScore: 85, valueScore: 96,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Lowest Price", "Pure Creatine", "Widely Available", "Beginner Friendly"],
    aiSummary: "The cheapest creatine on the market — a no-frills option for those who want proven strength benefits at minimum cost.",
  },
  {
    id: "p55", slug: "gnc-creatine-250g", brandId: "brand-008", categoryId: "cat-003",
    title: "GNC Creatine Monohydrate 250g",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAEBSE5ILkdEdQwwBhYtiRM1c98s-0wlOYcVqXHkRuIg&s=10",
    rating: 4.5, reviews: 5600, price: 22.16, originalPrice: 27.71,
    website: "GNC", delivery: "Free • 2 days", servingSize: "5g",
    ingredients: ["Creatine Monohydrate"],
    pros: ["Trusted brand", "Micronized", "Pure"],
    cons: ["Premium price"],
    bestFor: "Brand-conscious buyers",
    warnings: "Stay hydrated",
    country: "USA", manufacturer: "GNC Holdings",
    labTested: true, certificationIds: ["cert-006", "cert-003"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 95, cleanLabelScore: 95, valueScore: 80,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Micronized", "Pure", "Trusted Brand", "Premium Quality"],
    aiSummary: "A premium micronized creatine from GNC, offering the highest quality standards for those who prioritize brand trust.",
  },
  {
    id: "p56", slug: "dymatize-creatine-500g", brandId: "brand-004", categoryId: "cat-003",
    title: "Dymatize Creatine Monohydrate 500g",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQk0MwMDdwy3vuRduPW2G4ZDWRD-RP1_t7PVoh-frHEIQ&s=10",
    rating: 4.7, reviews: 4200, price: 25.49, originalPrice: 32.14,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "5g",
    ingredients: ["Creatine Monohydrate"],
    pros: ["Pure micronized", "500g value", "Trusted brand"],
    cons: ["Premium pricing"],
    bestFor: "Serious lifters",
    warnings: "Stay well hydrated",
    country: "USA", manufacturer: "Dymatize Nutrition",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 95, cleanLabelScore: 95, valueScore: 88,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["500g Value", "Pure Creatine", "Micronized", "Trusted Brand"],
    aiSummary: "A premium 500g creatine from Dymatize, offering pure micronized monohydrate at a solid value for serious athletes.",
  },
  {
    id: "p57", slug: "muscleblaze-creatine-500g", brandId: "brand-002", categoryId: "cat-003",
    title: "MuscleBlaze Creatine Monohydrate 500g",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRW3AExRzEPogdnJLbah7MxoHVFu5bxua5Rwb7k5KClKg&s",
    rating: 4.5, reviews: 9800, price: 13.29, originalPrice: 16.62,
    website: "HealthKart", delivery: "Free • 2 days", servingSize: "5g",
    ingredients: ["Creatine Monohydrate"],
    pros: ["Best-selling in India", "Great value 500g", "Lab tested"],
    cons: ["Not Creapure®"],
    bestFor: "Indian buyers seeking value",
    warnings: "Stay hydrated",
    country: "India", manufacturer: "HealthKart",
    labTested: true, certificationIds: ["cert-005", "cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 92, cleanLabelScore: 90, valueScore: 96,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["500g Value", "Best Seller", "Lab Tested", "Great Price"],
    aiSummary: "India's best-selling creatine offering exceptional value in the 500g size with lab-tested quality assurance.",
  },
  {
    id: "p58", slug: "rule1-creatine-500g", brandId: "brand-011", categoryId: "cat-003",
    title: "Rule 1 Creatine Monohydrate 500g",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVjOqdJejVadeu82nWDT_Tv3P_zrPhsH3Yfl2taa92Dg&s=10",
    rating: 4.7, reviews: 2900, price: 21.05, originalPrice: 26.6,
    website: "Amazon", delivery: "Free • 2 days", servingSize: "5g",
    ingredients: ["Creatine Monohydrate"],
    pros: ["Pure micronized", "Good value", "Trusted brand"],
    cons: ["Standard product"],
    bestFor: "Strength athletes",
    warnings: "Stay hydrated",
    country: "USA", manufacturer: "Rule 1 Proteins",
    labTested: true, certificationIds: ["cert-001", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 95, cleanLabelScore: 95, valueScore: 90,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["500g Value", "Pure Creatine", "Micronized", "Trusted Brand"],
    aiSummary: "A high-quality 500g creatine monohydrate from Rule 1, delivering pure micronized creatine at a competitive price.",
  },
  {
    id: "p59", slug: "myprotein-creatine-1kg", brandId: "brand-003", categoryId: "cat-003",
    title: "MyProtein Creatine Monohydrate 1kg",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKuXAeNDo_AQvXAthY-L-wtbMabD6wXOsB7Hwjiyd4Tw&s=10",
    rating: 4.6, reviews: 8500, price: 31.03, originalPrice: 38.79,
    website: "MyProtein", delivery: "Free • 5 days", servingSize: "5g",
    ingredients: ["Creatine Monohydrate"],
    pros: ["Massive 1kg value", "Pure monohydrate", "Global brand"],
    cons: ["Large pouch, storage needed"],
    bestFor: "Heavy creatine users",
    warnings: "Stay hydrated",
    country: "UK", manufacturer: "The Hut Group",
    labTested: true, certificationIds: ["cert-002", "cert-006"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 95, cleanLabelScore: 95, valueScore: 94,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["1kg Value", "Pure Creatine", "Best Cost Per Serving", "Global Brand"],
    aiSummary: "The ultimate creatine value — 1kg of pure monohydrate at the lowest cost per serving for serious long-term users.",
  },
  {
    id: "p60", slug: "herbalife-creatine", brandId: "brand-046", categoryId: "cat-003",
    title: "Herbalife Creatine Monohydrate",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRuXrc7MzRqJDFBI7POwe0IFrWFCeBNXNPCalHBmrnWA&s=10",
    rating: 4.2, reviews: 3200, price: 21.05, originalPrice: 26.6,
    website: "Herbalife", delivery: "Free • 3 days", servingSize: "5g",
    ingredients: ["Creatine Monohydrate"],
    pros: ["Global brand", "Pure creatine"],
    cons: ["Overpriced", "Limited availability"],
    bestFor: "Herbalife customers",
    warnings: "Stay well hydrated",
    country: "USA", manufacturer: "Herbalife Nutrition",
    labTested: true, certificationIds: ["cert-006", "cert-008"],
    verified: true, buyLinks: { amazon: "", flipkart: "", healthkart: "", nykaa: "", muscleblaze: "", iherb: "" },
    nutrition: { protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, calories: 0 },
    healthScore: 90, cleanLabelScore: 90, valueScore: 72,
    dietaryInfo: { vegetarian: true, vegan: true, glutenFree: true, lactoseFree: true },
    ingredientFlags: { containsArtificialSweetener: false, containsSoy: false, containsGluten: false, containsLactose: false, containsSugarAlcohol: false },
    highlights: ["Pure Creatine", "Global Brand", "Proven Formula"],
    aiSummary: "A standard creatine monohydrate from the global nutrition giant, offering reliable quality at a premium price.",
  },
];