export interface Brand {
  id: string;
  name: string;
  slug: string;
  logo: string;
  country: string;
  founded?: number;
  website: string;
  categories: string[];
  verified: boolean;
  description: string;
}

export const brands: Brand[] = [
  {
    id: "brand-001",
    name: "Optimum Nutrition",
    slug: "optimum-nutrition",
    logo: "/images/brands/optimum-nutrition.webp",
    country: "USA",
    founded: 1986,
    website: "https://www.optimumnutrition.com",
    categories: ["Whey", "Creatine", "Mass Gainer", "Pre Workout"],
    verified: true,
    description: "One of the world's most trusted sports nutrition brands.",
  },
  {
    id: "brand-002",
    name: "MuscleBlaze",
    slug: "muscleblaze",
    logo: "/images/brands/muscleblaze.webp",
    country: "India",
    founded: 2012,
    website: "https://www.muscleblaze.com",
    categories: ["Whey", "Creatine", "Multivitamin", "Fish Oil"],
    verified: true,
    description: "India's leading sports nutrition brand.",
  },
  {
    id: "brand-003",
    name: "MyProtein",
    slug: "myprotein",
    logo: "/images/brands/myprotein.webp",
    country: "United Kingdom",
    founded: 2004,
    website: "https://www.myprotein.com",
    categories: ["Whey", "Protein Bar", "Peanut Butter"],
    verified: true,
    description: "Global sports nutrition and active lifestyle brand.",
  },
  {
    id: "brand-004",
    name: "Dymatize",
    slug: "dymatize",
    logo: "/images/brands/dymatize.webp",
    country: "USA",
    founded: 1994,
    website: "https://dymatize.com",
    categories: ["Whey", "Creatine"],
    verified: true,
    description: "Premium performance nutrition brand.",
  },
  {
    id: "brand-005",
    name: "Avvatar",
    slug: "avvatar",
    logo: "/images/brands/avvatar.webp",
    country: "India",
    founded: 2020,
    website: "https://avvatarindia.com",
    categories: ["Whey", "Mass Gainer"],
    verified: true,
    description: "Indian whey made from fresh milk.",
  },
  {
    id: "brand-006",
    name: "Nakpro",
    slug: "nakpro",
    logo: "/images/brands/nakpro.webp",
    country: "India",
    founded: 2016,
    website: "https://nakpro.com",
    categories: ["Whey", "Creatine"],
    verified: true,
    description: "Affordable sports nutrition.",
  },
  {
    id: "brand-007",
    name: "AS-IT-IS",
    slug: "as-it-is",
    logo: "/images/brands/asitis.webp",
    country: "India",
    website: "https://asitisnutrition.com",
    categories: ["Whey", "Creatine"],
    verified: true,
    description: "Minimal ingredient supplements.",
  },
  {
    id: "brand-008",
    name: "GNC",
    slug: "gnc",
    logo: "/images/brands/gnc.webp",
    country: "USA",
    founded: 1935,
    website: "https://www.gnc.com",
    categories: ["Whey", "Fish Oil", "Multivitamin"],
    verified: true,
    description: "Global health and wellness retailer.",
  },
  {
    id: "brand-009",
    name: "NOW Foods",
    slug: "now-foods",
    logo: "/images/brands/now-foods.webp",
    country: "USA",
    founded: 1968,
    website: "https://www.nowfoods.com",
    categories: ["Fish Oil", "Multivitamin"],
    verified: true,
    description: "Natural health supplements.",
  },
  {
    id: "brand-010",
    name: "Cellucor",
    slug: "cellucor",
    logo: "/images/brands/cellucor.webp",
    country: "USA",
    founded: 2002,
    website: "https://cellucor.com",
    categories: ["Pre Workout"],
    verified: true,
    description: "Performance-focused pre-workout brand.",
  },
  {
    id: "brand-011",
    name: "Rule1 Proteins",
    slug: "rule1",
    logo: "/images/brands/rule1.webp",
    country: "USA",
    founded: 2015,
    website: "https://rule1proteins.com",
    categories: ["Whey", "Creatine"],
    verified: true,
    description: "High-quality sports nutrition at fair prices.",
  },
  {
    id: "brand-012",
    name: "Isopure",
    slug: "isopure",
    logo: "/images/brands/isopure.webp",
    country: "USA",
    founded: 1998,
    website: "https://isopure.com",
    categories: ["Whey"],
    verified: true,
    description: "Zero-carb, premium whey protein isolate.",
  },
  {
    id: "brand-013",
    name: "Labrada Nutrition",
    slug: "labrada",
    logo: "/images/brands/labrada.webp",
    country: "USA",
    founded: 1996,
    website: "https://labrada.com",
    categories: ["Whey", "Mass Gainer"],
    verified: true,
    description: "Science-based bodybuilding nutrition.",
  },
  {
    id: "brand-014",
    name: "BSN",
    slug: "bsn",
    logo: "/images/brands/bsn.webp",
    country: "USA",
    founded: 2001,
    website: "https://bsn.com",
    categories: ["Whey", "Pre Workout", "Mass Gainer"],
    verified: true,
    description: "Iconic sports nutrition brand.",
  },
  {
    id: "brand-015",
    name: "Kevin Levrone",
    slug: "kevin-levrone",
    logo: "/images/brands/kevin-levrone.webp",
    country: "USA",
    founded: 2015,
    website: "https://kevinlevrone.com",
    categories: ["Whey", "Creatine"],
    verified: true,
    description: "Premium supplements by the legendary bodybuilder.",
  },
  {
    id: "brand-016",
    name: "Ultimate Nutrition",
    slug: "ultimate-nutrition",
    logo: "/images/brands/ultimate-nutrition.webp",
    country: "USA",
    founded: 1979,
    website: "https://ultimatenutrition.com",
    categories: ["Whey", "Creatine", "Fish Oil"],
    verified: true,
    description: "Decades of sports nutrition expertise.",
  },
  {
    id: "brand-017",
    name: "Fuel One",
    slug: "fuel-one",
    logo: "/images/brands/fuel-one.webp",
    country: "India",
    founded: 2018,
    website: "https://fuelone.in",
    categories: ["Whey", "Mass Gainer"],
    verified: true,
    description: "Affordable Indian sports nutrition.",
  },
  {
    id: "brand-018",
    name: "Carbamide Forte",
    slug: "carbamide-forte",
    logo: "/images/brands/carbamide-forte.webp",
    country: "India",
    founded: 2017,
    website: "https://carbamideforte.com",
    categories: ["Whey", "Creatine", "Multivitamin"],
    verified: true,
    description: "Science-backed nutritional supplements.",
  },
  {
    id: "brand-019",
    name: "HK Vitals",
    slug: "hk-vitals",
    logo: "/images/brands/hk-vitals.webp",
    country: "India",
    website: "https://healthkart.com",
    categories: ["Fish Oil", "Multivitamin"],
    verified: true,
    description: "HealthKart's in-house wellness brand.",
  },
  {
    id: "brand-020",
    name: "Centrum",
    slug: "centrum",
    logo: "/images/brands/centrum.webp",
    country: "USA",
    founded: 1978,
    website: "https://centrum.com",
    categories: ["Multivitamin"],
    verified: true,
    description: "World's #1 multivitamin brand.",
  },
  {
    id: "brand-021",
    name: "One A Day",
    slug: "one-a-day",
    logo: "/images/brands/one-a-day.webp",
    country: "USA",
    founded: 1940,
    website: "https://oneaday.com",
    categories: ["Multivitamin"],
    verified: true,
    description: "Trusted daily multivitamins.",
  },
  {
    id: "brand-022",
    name: "Minimalist",
    slug: "minimalist",
    logo: "/images/brands/minimalist.webp",
    country: "India",
    founded: 2020,
    website: "https://beminimalist.co",
    categories: ["Serum", "Moisturizer", "Sunscreen"],
    verified: true,
    description: "Transparent, science-driven skincare.",
  },
  {
    id: "brand-023",
    name: "Cetaphil",
    slug: "cetaphil",
    logo: "/images/brands/cetaphil.webp",
    country: "USA",
    founded: 1947,
    website: "https://cetaphil.com",
    categories: ["Face Wash", "Moisturizer"],
    verified: true,
    description: "Gentle skincare for sensitive skin.",
  },
  {
    id: "brand-024",
    name: "CeraVe",
    slug: "cerave",
    logo: "/images/brands/cerave.webp",
    country: "USA",
    founded: 2005,
    website: "https://cerave.com",
    categories: ["Face Wash", "Moisturizer", "Sunscreen"],
    verified: true,
    description: "Dermatologist-developed skincare.",
  },
  {
    id: "brand-025",
    name: "Neutrogena",
    slug: "neutrogena",
    logo: "/images/brands/neutrogena.webp",
    country: "USA",
    founded: 1930,
    website: "https://neutrogena.com",
    categories: ["Face Wash", "Moisturizer", "Sunscreen"],
    verified: true,
    description: "Science-backed skincare solutions.",
  },
  {
    id: "brand-026",
    name: "Bioderma",
    slug: "bioderma",
    logo: "/images/brands/bioderma.webp",
    country: "France",
    founded: 1977,
    website: "https://bioderma.com",
    categories: ["Face Wash", "Moisturizer", "Sunscreen"],
    verified: true,
    description: "French dermatological skincare.",
  },
  {
    id: "brand-027",
    name: "COSRX",
    slug: "cosrx",
    logo: "/images/brands/cosrx.webp",
    country: "South Korea",
    founded: 2013,
    website: "https://cosrx.com",
    categories: ["Face Wash", "Serum", "Moisturizer"],
    verified: true,
    description: "Korean skincare with effective ingredients.",
  },
  {
    id: "brand-028",
    name: "Dot & Key",
    slug: "dot-key",
    logo: "/images/brands/dot-key.webp",
    country: "India",
    founded: 2019,
    website: "https://dotandkey.com",
    categories: ["Serum", "Moisturizer", "Sunscreen"],
    verified: true,
    description: "Fun, effective skincare for modern skin.",
  },
  {
    id: "brand-029",
    name: "The Derma Co",
    slug: "the-derma-co",
    logo: "/images/brands/the-derma-co.webp",
    country: "India",
    founded: 2020,
    website: "https://thedermaco.com",
    categories: ["Serum", "Face Wash", "Sunscreen"],
    verified: true,
    description: "Dermatologist-inspired skincare.",
  },
  {
    id: "brand-030",
    name: "Plum",
    slug: "plum",
    logo: "/images/brands/plum.webp",
    country: "India",
    founded: 2014,
    website: "https://plumgoodness.com",
    categories: ["Face Wash", "Moisturizer", "Body Wash"],
    verified: true,
    description: "Cruelty-free, plant-based skincare.",
  },
  {
    id: "brand-031",
    name: "Dove",
    slug: "dove",
    logo: "/images/brands/dove.webp",
    country: "USA",
    founded: 1957,
    website: "https://dove.com",
    categories: ["Body Wash", "Shampoo", "Moisturizer"],
    verified: true,
    description: "Real beauty with gentle care.",
  },
  {
    id: "brand-032",
    name: "Nivea",
    slug: "nivea",
    logo: "/images/brands/nivea.webp",
    country: "Germany",
    founded: 1911,
    website: "https://nivea.com",
    categories: ["Moisturizer", "Body Wash", "Sunscreen"],
    verified: true,
    description: "Trusted skincare since 1911.",
  },
  {
    id: "brand-033",
    name: "L'Oréal Paris",
    slug: "loreal",
    logo: "/images/brands/loreal.webp",
    country: "France",
    founded: 1909,
    website: "https://lorealparis.com",
    categories: ["Shampoo", "Serum", "Sunscreen"],
    verified: true,
    description: "Leading beauty brand worldwide.",
  },
  {
    id: "brand-034",
    name: "Himalaya",
    slug: "himalaya",
    logo: "/images/brands/himalaya.webp",
    country: "India",
    founded: 1930,
    website: "https://himalayawellness.com",
    categories: ["Face Wash", "Shampoo", "Multivitamin"],
    verified: true,
    description: "Herbal wellness and personal care.",
  },
  {
    id: "brand-035",
    name: "Mamaearth",
    slug: "mamaearth",
    logo: "/images/brands/mamaearth.webp",
    country: "India",
    founded: 2016,
    website: "https://mamaearth.in",
    categories: ["Face Wash", "Moisturizer", "Sunscreen", "Shampoo"],
    verified: true,
    description: "Toxin-free, natural personal care.",
  },
  {
    id: "brand-036",
    name: "Yoga Bar",
    slug: "yoga-bar",
    logo: "/images/brands/yoga-bar.webp",
    country: "India",
    founded: 2014,
    website: "https://theyogabar.com",
    categories: ["Protein Bar", "Granola", "Muesli"],
    verified: true,
    description: "Healthy snacks made from real ingredients.",
  },
  {
    id: "brand-037",
    name: "Pintola",
    slug: "pintola",
    logo: "/images/brands/pintola.webp",
    country: "India",
    founded: 2015,
    website: "https://pintola.com",
    categories: ["Peanut Butter"],
    verified: true,
    description: "All-natural peanut butter with no additives.",
  },
  {
    id: "brand-038",
    name: "Alpino",
    slug: "alpino",
    logo: "/images/brands/alpino.webp",
    country: "India",
    founded: 2016,
    website: "https://alpino.in",
    categories: ["Peanut Butter", "Trail Mix"],
    verified: true,
    description: "Healthy nut butters and snacks.",
  },
  {
    id: "brand-039",
    name: "True Elements",
    slug: "true-elements",
    logo: "/images/brands/true-elements.webp",
    country: "India",
    founded: 2015,
    website: "https://trueelements.in",
    categories: ["Oats", "Granola", "Muesli", "Trail Mix"],
    verified: true,
    description: "Clean, natural whole foods.",
  },
  {
    id: "brand-040",
    name: "RiteBite",
    slug: "ritebite",
    logo: "/images/brands/ritebite.webp",
    country: "India",
    founded: 2017,
    website: "https://ritebite.in",
    categories: ["Protein Bar", "Granola"],
    verified: true,
    description: "High-protein, low-sugar nutrition bars.",
  },
  {
    id: "brand-041",
    name: "The Whole Truth",
    slug: "the-whole-truth",
    logo: "/images/brands/the-whole-truth.webp",
    country: "India",
    founded: 2019,
    website: "https://thewholetruthfoods.com",
    categories: ["Protein Bar", "Peanut Butter", "Oats"],
    verified: true,
    description: "100% clean label foods with no hidden ingredients.",
  },
  {
    id: "brand-042",
    name: "Kellogg's",
    slug: "kelloggs",
    logo: "/images/brands/kelloggs.webp",
    country: "USA",
    founded: 1906,
    website: "https://kelloggs.com",
    categories: ["Oats", "Granola", "Muesli"],
    verified: true,
    description: "World's leading cereal company.",
  },
  {
    id: "brand-043",
    name: "Quaker",
    slug: "quaker",
    logo: "/images/brands/quaker.webp",
    country: "USA",
    founded: 1877,
    website: "https://quakeroats.com",
    categories: ["Oats", "Granola"],
    verified: true,
    description: "America's trusted oat brand.",
  },
  {
    id: "brand-044",
    name: "Ensure",
    slug: "ensure",
    logo: "/images/brands/ensure.webp",
    country: "USA",
    founded: 1973,
    website: "https://ensure.com",
    categories: ["Mass Gainer", "Multivitamin"],
    verified: true,
    description: "Complete balanced nutrition for all ages.",
  },
  {
    id: "brand-045",
    name: "Boost",
    slug: "boost",
    logo: "/images/brands/boost.webp",
    country: "USA",
    founded: 1988,
    website: "https://boost.com",
    categories: ["Mass Gainer", "Multivitamin"],
    verified: true,
    description: "Nutrition drinks for energy and strength.",
  },
  {
    id: "brand-046",
    name: "Herbalife",
    slug: "herbalife",
    logo: "/images/brands/herbalife.webp",
    country: "USA",
    founded: 1980,
    website: "https://herbalife.com",
    categories: ["Whey", "Multivitamin"],
    verified: true,
    description: "Global nutrition and weight management brand.",
  },
  {
    id: "brand-047",
    name: "Amway Nutrilite",
    slug: "nutrilite",
    logo: "/images/brands/nutrilite.webp",
    country: "USA",
    founded: 1934,
    website: "https://nutrilite.com",
    categories: ["Multivitamin"],
    verified: true,
    description: "World's leading vitamin and supplement brand.",
  },
  {
    id: "brand-048",
    name: "Biotin",
    slug: "biotin",
    logo: "/images/brands/biotin.webp",
    country: "India",
    website: "https://biotin.in",
    categories: ["Multivitamin"],
    verified: true,
    description: "Hair, skin, and nail supplements.",
  },
  {
    id: "brand-049",
    name: "Mcaffeine",
    slug: "mcaffeine",
    logo: "/images/brands/mcaffeine.webp",
    country: "India",
    founded: 2016,
    website: "https://mcaffeine.com",
    categories: ["Body Wash", "Moisturizer"],
    verified: true,
    description: "India's first caffeinated personal care brand.",
  },
  {
    id: "brand-050",
    name: "Wow Skin Science",
    slug: "wow-skin-science",
    logo: "/images/brands/wow-skin-science.webp",
    country: "India",
    founded: 2014,
    website: "https://wowskinscience.com",
    categories: ["Face Wash", "Shampoo", "Body Wash", "Serum"],
    verified: true,
    description: "Natural, toxin-free beauty products.",
  },
];