/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ApiElevenlabsTokenRouteImport } from './routes/api/elevenlabs.token'

const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElevenlabsTokenRoute = ApiElevenlabsTokenRouteImport.update({
  id: '/api/elevenlabs/token',
  path: '/api/elevenlabs/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/elevenlabs/token': typeof ApiElevenlabsTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/elevenlabs/token': typeof ApiElevenlabsTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/elevenlabs/token': typeof ApiElevenlabsTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/categories'
    | '/compare'
    | '/profile'
    | '/rewards'
    | '/product/$slug'
    | '/api/elevenlabs/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/categories'
    | '/compare'
    | '/profile'
    | '/rewards'
    | '/product/$slug'
    | '/api/elevenlabs/token'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/categories'
    | '/compare'
    | '/profile'
    | '/rewards'
    | '/product/$slug'
    | '/api/elevenlabs/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CategoriesRoute: typeof CategoriesRoute
  CompareRoute: typeof CompareRoute
  ProfileRoute: typeof ProfileRoute
  RewardsRoute: typeof RewardsRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiElevenlabsTokenRoute: typeof ApiElevenlabsTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elevenlabs/token': {
      id: '/api/elevenlabs/token'
      path: '/api/elevenlabs/token'
      fullPath: '/api/elevenlabs/token'
      preLoaderRoute: typeof ApiElevenlabsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CategoriesRoute: CategoriesRoute,
  CompareRoute: CompareRoute,
  ProfileRoute: ProfileRoute,
  RewardsRoute: RewardsRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiElevenlabsTokenRoute: ApiElevenlabsTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
